# Copyright (c) 2018, NVIDIA CORPORATION.

# Usage:
#   conda build . -c defaults -c conda-forge -c numba -c rapidsai -c pytorch
{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') %}
{% set git_revision_count=environ.get('GIT_DESCRIBE_NUMBER', 0) %}
{% set cuda_version='.'.join(environ.get('CUDA', 'unknown').split('.')[:2]) %}
{% set py_version=environ.get('CONDA_PY', 36) %}

package:
  name: cuml
  version: {{ version }}

source:
  path: ../../..

build:
  number: {{ git_revision_count }}
  string: cuda{{ cuda_version }}_py{{ py_version }}_{{ git_revision_count }}
  script_env:
    - CC
    - CXX
    - BUILD_ABI

requirements:
  build:
    - python x.x
    - setuptools
    - cython>=0.29,<0.30
    - cmake>=3.14
    - cudf 0.9*
    - libcuml={{ version }}
    - libcumlprims=0.9
    - cudatoolkit {{ cuda_version }}.*
  run:
    - python x.x
    - cudf 0.9*
    - libcuml={{ version }}
    - libcumlprims=0.9
    - nvidia::nccl >=2,<3
    - {{ pin_compatible('cudatoolkit', max_pin='x.x') }}

about:
  home: http://rapids.ai/
  license: Apache-2.0
  # license_file: LICENSE
  summary: cuML library
