# Copyright (c) 2018-2022, NVIDIA CORPORATION.

# Usage:
#   conda build . -c conda-forge -c numba -c rapidsai -c pytorch
{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version = version.split('.')[0] + '.' + version.split('.')[1] %}
{% set cuda_version = '.'.join(environ['RAPIDS_CUDA_VERSION'].split('.')[:2]) %}
{% set cuda_major = cuda_version.split('.')[0] %}
{% set py_version = environ['CONDA_PY'] %}

package:
  name: cuml-split
  # version: {{ version }}

source:
  git_url: ../../..

build:
  script_env:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - PARALLEL_LEVEL
    - CMAKE_GENERATOR
    - CMAKE_C_COMPILER_LAUNCHER
    - CMAKE_CXX_COMPILER_LAUNCHER
    - CMAKE_CUDA_COMPILER_LAUNCHER
    - SCCACHE_S3_KEY_PREFIX=cuml-aarch64 # [aarch64]
    - SCCACHE_S3_KEY_PREFIX=cuml-linux64 # [linux64]
    - SCCACHE_BUCKET
    - SCCACHE_REGION
    - SCCACHE_IDLE_TIMEOUT

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake {{ cmake_version }}
    - ninja
    - sysroot_{{ target_platform }} {{ sysroot_version }}
  host:
    - cython >=0.29,<0.30
    - python x.x
    - scikit-build >=0.13.1
    - setuptools
  run:
    - python x.x

outputs:
  - name: cuml
    version: {{ version }}
    build:
      number: {{ GIT_DESCRIBE_NUMBER }}
      string: cuda{{ cuda_major }}_py{{ py_version }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
      ignore_run_exports_from:
        - {{ compiler('cuda') }}
    requirements:
      build:
        - {{ compiler('cuda') }} {{ cuda_version }}
      host:
        - cuda-python >=11.7.1,<12.0
        - cudatoolkit ={{ cuda_version }}
        - cudf ={{ minor_version }}
        - libcublas {{ libcublas_host_version }}
        - libcublas-dev {{ libcublas_host_version }}
        - libcuml ={{ version }}
        - libcumlprims ={{ minor_version }}
        - libcurand {{ libcurand_host_version }}
        - libcurand-dev {{ libcurand_host_version }}
        - libcusolver {{ libcusolver_host_version }}
        - libcusolver-dev {{ libcusolver_host_version }}
        - libcusparse {{ libcusparse_host_version }}
        - libcusparse-dev {{ libcusparse_host_version }}
        - pylibraft ={{ minor_version }}
        - raft-dask ={{ minor_version }}
        - treelite {{ treelite_version }}
      run:
        - {{ pin_compatible('cudatoolkit', max_pin='x', min_pin='x') }}
        - cuda-python >=11.7.1,<12.0
        - cudf ={{ minor_version }}
        - cupy >=7.8.0,<12.0.0a0
        - dask-cudf ={{ minor_version }}
        - dask >=2022.12.0
        - distributed >=2022.12.0
        - joblib >=0.11
        - libcuml ={{ version }}
        - libcumlprims ={{ minor_version }}
        - pylibraft ={{ minor_version }}
        - raft-dask ={{ minor_version }}
        - treelite {{ treelite_version }}
      tests:                                 # [linux64]
        requirements:                        # [linux64]
          - cudatoolkit ={{ cuda_version }}  # [linux64]
        imports:                             # [linux64]
          - cuml
      about:
        home: https://rapids.ai/
        license: Apache-2.0
        summary: cuML library
  - name: cuml-cpu
    version: {{ version }}
    script: install_cuml_cpu.sh
    build:
      number: {{ GIT_DESCRIBE_NUMBER }}
      string: py{{ py_version }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
    requirements:
      run:
        - {{ pin_compatible('cudatoolkit', max_pin='x', min_pin='x') }}
        - scikit-learn=1.2
        - hdbscan=0.8.29
        - umap-learn=0.5.3
        - nvtx
      about:
        home: https://rapids.ai/
        license: Apache-2.0
        summary: cuML library
