# Copyright (c) 2018, NVIDIA CORPORATION.

# Usage:
#   conda build . -c defaults -c conda-forge -c numba -c rapidsai -c pytorch
{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version =  version.split('.')[0] + '.' + version.split('.')[1] %}
{% set git_revision_count=environ.get('GIT_DESCRIBE_NUMBER', 0) %}
{% set cuda_version='.'.join(environ.get('CUDA', 'unknown').split('.')[:2]) %}
{% set py_version=environ.get('CONDA_PY', 36) %}

package:
  name: cuml
  version: {{ version }}

source:
  path: ../../..

build:
  number: {{ git_revision_count }}
  string: cuda{{ cuda_version }}_py{{ py_version }}_{{ git_revision_count }}
  script_env:
    - CC
    - CXX
    - VERSION_SUFFIX

requirements:
  build:
    - python x.x
    - setuptools
    - cython>=0.29,<0.30
    - cmake>=3.14
    - protobuf >=3.4.1,<4.0.0
    - cudf {{ minor_version }}
    - libcuml={{ version }}
    - libcumlprims=0.14.*
    - cudatoolkit {{ cuda_version }}.*
    - ucx-py {{ minor_version }}
  run:
    - python x.x
    - cudf {{ minor_version }}
    - dask-cudf {{ minor_version }}
    - libcuml={{ version }}
    - libcumlprims=0.14.*
    - cupy>=7,<8.0.0a0
    - nccl>=2.5
    - ucx-py {{ minor_version }}
    - dask>=2.12.0
    - distributed>=2.12.0
    - joblib >=0.11
    - {{ pin_compatible('cudatoolkit', max_pin='x.x') }}

about:
  home: http://rapids.ai/
  license: Apache-2.0
  # license_file: LICENSE
  summary: cuML library
