# Copyright (c) 2018, NVIDIA CORPORATION.

# Usage:
#   conda build . -c defaults -c conda-forge -c numba -c rapidsai -c pytorch
{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') %}
{% set git_revision_count=environ.get('GIT_DESCRIBE_NUMBER', 0) %}
{% set cuda_version='.'.join(environ.get('CUDA', 'unknown').split('.')[:2]) %}
{% set py_version=environ.get('CONDA_PY', 35) %}
package:
  name: cuml
  version: {{ version }}

source:
  path: ../..

build:
  number: {{ git_revision_count }}
  string: cuda{{ cuda_version }}_py{{ py_version }}_{{ git_revision_count }}
  script_env:
    - CC
    - CXX

requirements:
  build:
    - python x.x
    - setuptools
    - cython
    - cmake 3.12
    - cudf 0.4.0.*
    - libcuml 0.4.0.*
  run:
    - python x.x
    - setuptools
    - cudf 0.4.0.*
    - libcuml 0.4.0.*

about:
  home: http://rapids.ai/
  license: Apache-2.0
  # license_file: LICENSE
  summary: cuML library
