# Copyright (c) 2018-2023, NVIDIA CORPORATION.

{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') %}
{% set minor_version = version.split('.')[0] + '.' + version.split('.')[1] %}
{% set cuda_version = '.'.join(environ['RAPIDS_CUDA_VERSION'].split('.')[:2]) %}
{% set cuda_major = cuda_version.split('.')[0] %}
{% set py_version = environ['CONDA_PY'] %}
{% set date_string = environ['RAPIDS_DATE_STRING'] %}

package:
  name: cuml
  version: {{ version }}

source:
  git_url: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: cuda{{ cuda_major }}_py{{ py_version }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_SESSION_TOKEN
    - CMAKE_C_COMPILER_LAUNCHER
    - CMAKE_CUDA_COMPILER_LAUNCHER
    - CMAKE_CXX_COMPILER_LAUNCHER
    - CMAKE_GENERATOR
    - PARALLEL_LEVEL
    - SCCACHE_BUCKET
    - SCCACHE_IDLE_TIMEOUT
    - SCCACHE_REGION
    - SCCACHE_S3_KEY_PREFIX=cuml-aarch64 # [aarch64]
    - SCCACHE_S3_KEY_PREFIX=cuml-linux64 # [linux64]
    - SCCACHE_S3_USE_SSL
  ignore_run_exports_from:
    {% if cuda_major == "11" %}
    - {{ compiler('cuda11') }}
    {% endif %}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    {% if cuda_major == "11" %}
    - {{ compiler('cuda11') }} ={{ cuda_version }}
    {% else %}
    - {{ compiler('cuda') }}
    {% endif %}
    - cuda-version ={{ cuda_version }}
    - cmake {{ cmake_version }}
    - ninja
    - sysroot_{{ target_platform }} {{ sysroot_version }}
  host:
    - cuda-version ={{ cuda_version }}
    {% if cuda_major == "11" %}
    - cuda-python ==11.7.1
    - cudatoolkit
    {% else %}
    - cuda-python ==12.0.0
    {% endif %}
    - cudf ={{ minor_version }}
    - cython >=0.29,<0.30
    - libcuml ={{ version }}
    - libcumlprims ={{ minor_version }}
    - pylibraft ={{ minor_version }}
    - python x.x
    - raft-dask ={{ minor_version }}
    - scikit-build >=0.13.1
    - setuptools
    - treelite {{ treelite_version }}
  run:
    - {{ pin_compatible('cuda-version', max_pin='x', min_pin='x') }}
    {% if cuda_major == "11" %}
    - cudatoolkit
    {% endif %}
    - cudf ={{ minor_version }}
    - cupy >=12.0.0
    - dask-cudf ={{ minor_version }}
    - dask >=2023.5.1
    - dask-core>=2023.5.1
    - distributed >=2023.5.1
    - joblib >=0.11
    - libcuml ={{ version }}
    - libcumlprims ={{ minor_version }}
    - pylibraft ={{ minor_version }}
    - python x.x
    - raft-dask ={{ minor_version }}
    - treelite {{ treelite_version }}

tests:
  requirements:
    - cuda-version ={{ cuda_version }}
  imports:
    - cuml

about:
  home: https://rapids.ai/
  license: Apache-2.0
  # license_file: LICENSE
  summary: cuML library
