# Copyright (c) 2018-2022, NVIDIA CORPORATION.

# Usage:
#   conda build . -c conda-forge -c numba -c rapidsai -c pytorch
{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version =  version.split('.')[0] + '.' + version.split('.')[1] %}
{% set cuda_version='.'.join(environ.get('CUDA', 'unknown').split('.')[:2]) %}
{% set cuda_major=cuda_version.split('.')[0] %}
{% set py_version=environ.get('CONDA_PY', 36) %}
{% set ucx_py_version=environ.get('UCX_PY_VERSION') %}

package:
  name: cuml
  version: {{ version }}

source:
  git_url: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: cuda{{ cuda_major }}_py{{ py_version }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - CC
    - CXX
    - VERSION_SUFFIX

requirements:
  build:
    - python x.x
    - setuptools
    - cython>=0.29,<0.30
    - cmake>=3.20.1
    - treelite=2.3.0
    - cudf {{ minor_version }}
    - libcuml={{ version }}
    - libcumlprims {{ minor_version }}
    - pyraft {{ minor_version }}
    - cudatoolkit {{ cuda_version }}.*
    - ucx-py {{ ucx_py_version }}
    - ucx-proc=*=gpu
    - cuda-python >=11.5,<12.0
  run:
    - python x.x
    - cudf {{ minor_version }}
    - dask-cudf {{ minor_version }}
    - libcuml={{ version }}
    - libcumlprims {{ minor_version }}
    - pyraft {{ minor_version }}
    - cupy>=7.8.0,<11.0.0a0
    - treelite=2.3.0
    - nccl>=2.9.9
    - ucx-py {{ ucx_py_version }}
    - ucx-proc=*=gpu
    - dask==2022.03.0
    - distributed==2022.03.0
    - joblib >=0.11
    - {{ pin_compatible('cudatoolkit', max_pin='x', min_pin='x') }}
    - cuda-python >=11.5,<12.0

tests:                                 # [linux64]
  requirements:                        # [linux64]
    - cudatoolkit {{ cuda_version }}.* # [linux64]
  imports:                             # [linux64]
    - cuml                             # [linux64]

about:
  home: http://rapids.ai/
  license: Apache-2.0
  # license_file: LICENSE
  summary: cuML library
