# https://github.com/actions/labeler#common-examples
# Adapted from https://github.com/rapidsai/cuml/blob/main/.github/CODEOWNERS
# Labels culled from https://github.com/rapidsai/cuml/labels

Cython / Python:
  - changed-files:
    - any-glob-to-any-file:
      - 'python/**'
      - 'notebooks/**'

CUDA/C++:
  - changed-files:
    - any-glob-to-any-file:
      - 'cpp/**'

CMake:
  - changed-files:
    - any-glob-to-any-file:
      - '**/CMakeLists.txt'
      - '**/cmake/**'

ci:
  - changed-files:
    - any-glob-to-any-file:
      - 'ci/**'

conda:
  - changed-files:
    - any-glob-to-any-file:
      - 'conda/**'
