#Configuration File for CodeCov
coverage:
  status:
    project: off
    patch: off
comment:
  behavior: new
flags:
  non-dask:
    paths:
      - "!python/cuml/dask/"
  dask:
    paths:
      - "python/cuml/dask/"
