# Copyright (c) 2018-2022, NVIDIA CORPORATION.

# Usage:
#   conda build . -c conda-forge -c nvidia -c rapidsai -c pytorch
{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version =  version.split('.')[0] + '.' + version.split('.')[1] %}
{% set cuda_version='.'.join(environ.get('CUDA', '9.2').split('.')[:2]) %}
{% set cuda_major=cuda_version.split('.')[0] %}
{% set ucx_py_version=environ.get('UCX_PY_VERSION') %}
package:
  name: libcuml
  version: {{ version }}

source:
  git_url: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: cuda{{ cuda_major }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - CC
    - CXX
    - CUDAHOSTCXX
    - PARALLEL_LEVEL
    - VERSION_SUFFIX
    - PROJECT_FLASH
    - CMAKE_GENERATOR
    - CMAKE_C_COMPILER_LAUNCHER
    - CMAKE_CXX_COMPILER_LAUNCHER
    - CMAKE_CUDA_COMPILER_LAUNCHER
    - SCCACHE_S3_KEY_PREFIX=libcuml-aarch64 # [aarch64]
    - SCCACHE_S3_KEY_PREFIX=libcuml-linux64 # [linux64]
    - SCCACHE_BUCKET=rapids-sccache
    - SCCACHE_REGION=us-west-2
    - SCCACHE_IDLE_TIMEOUT=32768

requirements:
  build:
    - cmake>=3.20.1,<3.23
  host:
    - nccl>=2.9.9
    - cudf {{ minor_version }}
    - cudatoolkit {{ cuda_version }}.*
    - ucx-py {{ ucx_py_version }}
    - ucx-proc=*=gpu
    - libcumlprims {{ minor_version }}
    - libraft-headers {{ minor_version }}
    - libraft-distance {{ minor_version }}
    - libraft-nn {{ minor_version }}
    - lapack
    - treelite=2.3.0
    - faiss-proc=*=cuda
    - gtest=1.10.0
    - gmock
    - libfaiss 1.7.0 *_cuda
  run:
    - libcumlprims {{ minor_version }}
    - libraft-headers {{ minor_version }}
    - libraft-distance {{ minor_version }}
    - libraft-nn {{ minor_version }}
    - cudf {{ minor_version }}
    - nccl>=2.9.9
    - ucx-py {{ ucx_py_version }}
    - ucx-proc=*=gpu
    - {{ pin_compatible('cudatoolkit', max_pin='x', min_pin='x') }}
    - treelite=2.3.0
    - faiss-proc=*=cuda
    - libfaiss 1.7.0 *_cuda
    - libcusolver>=11.2.1

about:
  home: http://rapids.ai/
  license: Apache-2.0
  # license_file: LICENSE
  summary: libcuml library
