# Copyright (c) 2018, NVIDIA CORPORATION.

# Usage:
#   conda build . -c defaults -c conda-forge -c nvidia -c rapidsai -c pytorch
{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version =  version.split('.')[0] + '.' + version.split('.')[1] %}
{% set cuda_version='.'.join(environ.get('CUDA', '9.2').split('.')[:2]) %}
{% set cuda_major = environ.get('CUDA', '9.2').split('.')[0] %}
{% set cuda_minor = environ.get('CUDA', '9.2').split('.')[1] %}
package:
  name: libcuml
  version: {{ version }}

source:
  git_url: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: cuda{{ cuda_version }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - CC
    - CXX
    - CUDAHOSTCXX
    - PARALLEL_LEVEL
    - VERSION_SUFFIX

requirements:
  build:
    - cmake>=3.14
    - clang=8.0.1
    - clang-tools=8.0.1
  host:
    - nccl 2.5.*
    - cudf {{ minor_version }}
    - cudatoolkit {{ cuda_version }}.*
    - ucx-py {{ minor_version }}
    - libcumlprims=0.15.0a200622
    - lapack
    - treelite=0.92
  run:
    - libcumlprims=0.15.0a200622
    - cudf {{ minor_version }}
    - nccl>=2.5
    - ucx-py {{ minor_version }}
    - {{ pin_compatible('cudatoolkit', max_pin='x.x') }}
    - treelite=0.92

about:
  home: http://rapids.ai/
  license: Apache-2.0
  # license_file: LICENSE
  summary: libcuml library
