# Copyright (c) 2018-2024, NVIDIA CORPORATION.

{% set version = environ['RAPIDS_PACKAGE_VERSION'].lstrip('v') %}
{% set minor_version = version.split('.')[0] + '.' + version.split('.')[1] %}
{% set cuda_version = '.'.join(environ['RAPIDS_CUDA_VERSION'].split('.')[:2]) %}
{% set cuda_major = cuda_version.split('.')[0] %}
{% set date_string = environ['RAPIDS_DATE_STRING'] %}

package:
  name: libcuml-split

source:
  path: ../../..

build:
  ignore_run_exports_from:
    {% if cuda_major == "11" %}
    - {{ compiler('cuda11') }}
    {% endif %}
  script_env:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_SESSION_TOKEN
    - CMAKE_C_COMPILER_LAUNCHER
    - CMAKE_CUDA_COMPILER_LAUNCHER
    - CMAKE_CXX_COMPILER_LAUNCHER
    - CMAKE_GENERATOR
    - PARALLEL_LEVEL
    - SCCACHE_BUCKET
    - SCCACHE_IDLE_TIMEOUT
    - SCCACHE_REGION
    - SCCACHE_S3_KEY_PREFIX=libcuml-aarch64 # [aarch64]
    - SCCACHE_S3_KEY_PREFIX=libcuml-linux64 # [linux64]
    - SCCACHE_S3_USE_SSL

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    {% if cuda_major == "11" %}
    - {{ compiler('cuda11') }} ={{ cuda_version }}
    {% else %}
    - {{ compiler('cuda') }}
    {% endif %}
    - cuda-version ={{ cuda_version }}
    - cmake {{ cmake_version }}
    - ninja
    - {{ stdlib("c") }}
  host:
    - cuda-version ={{ cuda_version }}
    {% if cuda_major == "11" %}
    - cudatoolkit
    - libcublas {{ cuda11_libcublas_host_version }}
    - libcublas-dev {{ cuda11_libcublas_host_version }}
    - libcufft {{ cuda11_libcufft_host_version }}
    - libcufft-dev {{ cuda11_libcufft_host_version }}
    - libcurand {{ cuda11_libcurand_host_version }}
    - libcurand-dev {{ cuda11_libcurand_host_version }}
    - libcusolver {{ cuda11_libcusolver_host_version }}
    - libcusolver-dev {{ cuda11_libcusolver_host_version }}
    - libcusparse {{ cuda11_libcusparse_host_version }}
    - libcusparse-dev {{ cuda11_libcusparse_host_version }}
    {% else %}
    - cuda-cudart-dev
    - libcublas-dev
    - libcufft-dev
    - libcurand-dev
    - libcusolver-dev
    - libcusparse-dev
    {% endif %}
    - fmt {{ fmt_version }}
    - libcumlprims ={{ minor_version }}
    - libcuvs ={{ minor_version }}
    - libraft-headers ={{ minor_version }}
    - librmm ={{ minor_version }}
    - spdlog {{ spdlog_version }}
    - treelite {{ treelite_version }}

outputs:
  - name: libcuml
    version: {{ version }}
    script: install_libcuml.sh
    build:
      number: {{ GIT_DESCRIBE_NUMBER }}
      string: cuda{{ cuda_major }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
      ignore_run_exports_from:
        {% if cuda_major == "11" %}
        - {{ compiler('cuda11') }}
        {% else %}
        - {{ compiler('cuda') }}
        - cuda-cudart-dev
        {% endif %}
    requirements:
      build:
        - cmake {{ cmake_version }}
      host:
        - cuda-version ={{ cuda_version }}
        {% if cuda_major != "11" %}
        - cuda-cudart-dev
        {% endif %}
      run:
        - {{ pin_compatible('cuda-version', max_pin='x', min_pin='x') }}
        {% if cuda_major == "11" %}
        - cudatoolkit
        - libcublas {{ cuda11_libcublas_run_version }}
        - libcufft {{ cuda11_libcufft_run_version }}
        - libcurand {{ cuda11_libcurand_run_version }}
        - libcusolver {{ cuda11_libcusolver_run_version }}
        - libcusparse {{ cuda11_libcusparse_run_version }}
        {% else %}
        - cuda-cudart
        - libcublas
        - libcufft
        - libcurand
        - libcusolver
        - libcusparse
        {% endif %}
        - libcumlprims ={{ minor_version }}
        - libcuvs ={{ minor_version }}
        - librmm ={{ minor_version }}
        - treelite {{ treelite_version }}
    about:
      home: https://rapids.ai/
      license: Apache-2.0
      license_file: LICENSE
      summary: libcuml library
  - name: libcuml-tests
    version: {{ version }}
    script: install_libcuml_tests.sh
    build:
      number: {{ GIT_DESCRIBE_NUMBER }}
      string: cuda{{ cuda_major }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
      ignore_run_exports_from:
        {% if cuda_major == "11" %}
        - {{ compiler('cuda11') }}
        {% else %}
        - {{ compiler('cuda') }}
        - cuda-cudart-dev
        {% endif %}
    requirements:
      build:
        - cmake {{ cmake_version }}
      host:
        - cuda-version ={{ cuda_version }}
        {% if cuda_major != "11" %}
        - cuda-cudart-dev
        {% endif %}
      run:
        - {{ pin_compatible('cuda-version', max_pin='x', min_pin='x') }}
        {% if cuda_major == "11" %}
        - cudatoolkit
        {% else %}
        - cuda-cudart
        {% endif %}
        - {{ pin_subpackage('libcuml', exact=True) }}
    about:
      home: https://rapids.ai/
      license: Apache-2.0
      license_file: LICENSE
      summary: libcuml test & benchmark executables
