# Copyright (c) 2018-2023, NVIDIA CORPORATION.

{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') %}
{% set minor_version = version.split('.')[0] + '.' + version.split('.')[1] %}
{% set cuda_version = '.'.join(environ['RAPIDS_CUDA_VERSION'].split('.')[:2]) %}
{% set cuda_major = cuda_version.split('.')[0] %}
{% set cuda_spec = ">=" + cuda_major ~ ",<" + (cuda_major | int + 1) ~ ".0a0" %} # i.e. >=11,<12.0a0
{% set date_string = environ['RAPIDS_DATE_STRING'] %}

package:
  name: libcuml-split

source:
  git_url: ../../..

build:
  script_env:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_SESSION_TOKEN
    - CMAKE_C_COMPILER_LAUNCHER
    - CMAKE_CUDA_COMPILER_LAUNCHER
    - CMAKE_CXX_COMPILER_LAUNCHER
    - CMAKE_GENERATOR
    - PARALLEL_LEVEL
    - SCCACHE_BUCKET
    - SCCACHE_IDLE_TIMEOUT
    - SCCACHE_REGION
    - SCCACHE_S3_KEY_PREFIX=libcuml-aarch64 # [aarch64]
    - SCCACHE_S3_KEY_PREFIX=libcuml-linux64 # [linux64]
    - SCCACHE_S3_USE_SSL

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    {% if cuda_major == "11" %}
    - {{ compiler('cuda11') }} {{ cuda_version }}
    {% else %}
    - {{ compiler('cuda') }} {{ cuda_version }}
    - cuda-cudart {{ cuda_version }}
    - cuda-cudart-dev {{ cuda_version }}
    - cuda-cudart-static {{ cuda_version }}
    {% endif %}
    - cmake {{ cmake_version }}
    - ninja
    - sysroot_{{ target_platform }} {{ sysroot_version }}
  host:
    - gmock
    - gtest {{ gtest_version }}
    - lapack
    {% if cuda_major == "11" %}
    - cudatoolkit ={{ cuda_version }}
    - libcublas {{ cuda11_libcublas_host_version }}
    - libcublas-dev {{ cuda11_libcublas_host_version }}
    - libcufft {{ cuda11_libcufft_host_version }}
    - libcufft-dev {{ cuda11_libcufft_host_version }}
    - libcurand {{ cuda11_libcurand_host_version }}
    - libcurand-dev {{ cuda11_libcurand_host_version }}
    - libcusolver {{ cuda11_libcusolver_host_version }}
    - libcusolver-dev {{ cuda11_libcusolver_host_version }}
    - libcusparse {{ cuda11_libcusparse_host_version }}
    - libcusparse-dev {{ cuda11_libcusparse_host_version }}
      # Ignore faiss in CUDA 12 for now
    - libfaiss>=1.7.1
    - faiss-proc=*=cuda
    {% else %}
    - cuda-cudart {{ cuda_version }}
    - cuda-cudart-dev {{ cuda_version }}
    - cuda-cudart-static {{ cuda_version }}
    - libcublas {{ libcublas_host_version }}
    - libcublas-dev {{ libcublas_host_version }}
    - libcufft {{ libcufft_host_version }}
    - libcufft-dev {{ libcufft_host_version }}
    - libcurand {{ libcurand_host_version }}
    - libcurand-dev {{ libcurand_host_version }}
    - libcusolver {{ libcusolver_host_version }}
    - libcusolver-dev {{ libcusolver_host_version }}
    - libcusparse {{ libcusparse_host_version }}
    - libcusparse-dev {{ libcusparse_host_version }}
    {% endif %}
    # - libcumlprims ={{ minor_version }}
    - libraft ={{ minor_version }}
    - libraft-headers ={{ minor_version }}
    - librmm ={{ minor_version }}
    - treelite {{ treelite_version }}

outputs:
  - name: libcuml
    version: {{ version }}
    script: install_libcuml.sh
    build:
      number: {{ GIT_DESCRIBE_NUMBER }}
      string: cuda{{ cuda_major }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
      ignore_run_exports_from:
        - {{ compiler('cuda') }}
    requirements:
      build:
        - cmake {{ cmake_version }}
      run:
        {% if cuda_major == "11" %}
        - cudatoolkit {{ cuda_spec }}
        - libcublas {{ cuda11_libcublas_run_version }}
        - libcublas-dev {{ cuda11_libcublas_run_version }}
        - libcufft {{ cuda11_libcufft_run_version }}
        - libcurand {{ cuda11_libcurand_run_version }}
        - libcusparse {{ cuda11_libcusparse_run_version }}
        - libcusparse-dev {{ cuda11_libcusparse_run_version }}
        # Ignore faiss in CUDA 12 for now
        - libfaiss>=1.7.1
        - faiss-proc=*=cuda
        {% else %}
        - cuda-cudart {{ cuda_spec }}
        - cuda-cudart-dev {{ cuda_spec }}
        - cuda-cudart-static {{ cuda_spec }}
        - libcublas {{ libcublas_run_version }}
        - libcublas-dev {{ libcublas_run_version }}
        - libcufft {{ libcufft_run_version }}
        - libcurand {{ libcurand_run_version }}
        - libcusparse {{ libcusparse_run_version }}
        - libcusparse-dev {{ libcusparse_run_version }}
        {% endif %}
        # - libcumlprims ={{ minor_version }}
        - libraft ={{ minor_version }}
        - libraft-headers ={{ minor_version }}
        - librmm ={{ minor_version }}
        - treelite {{ treelite_version }}
    about:
      home: https://rapids.ai/
      license: Apache-2.0
      summary: libcuml library
  - name: libcuml-tests
    version: {{ version }}
    script: install_libcuml_tests.sh
    build:
      number: {{ GIT_DESCRIBE_NUMBER }}
      string: cuda{{ cuda_major }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
      ignore_run_exports_from:
        - {{ compiler('cuda') }}
    requirements:
      build:
        - cmake {{ cmake_version }}
      run:
        {% if cuda_major == "11" %}
        - cudatoolkit {{ cuda_spec }}
        {% else %}
        - cuda-cudart {{ cuda_spec }}
        - cuda-cudart-dev {{ cuda_spec }}
        - cuda-cudart-static {{ cuda_spec }}
        {% endif %}
        - {{ pin_subpackage('libcuml', exact=True) }}
        - gtest {{ gtest_version }}
        - gmock {{ gtest_version }}
    about:
      home: https://rapids.ai/
      license: Apache-2.0
      summary: libcuml test & benchmark executables
