# Copyright (c) 2018-2022, NVIDIA CORPORATION.

# Usage:
#   conda build . -c conda-forge -c nvidia -c rapidsai -c pytorch
{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version = version.split('.')[0] + '.' + version.split('.')[1] %}
{% set cuda_version = '.'.join(environ['RAPIDS_CUDA_VERSION'].split('.')[:2]) %}
{% set cuda_major = cuda_version.split('.')[0] %}
{% set cuda_spec = ">=" + cuda_major ~ ",<" + (cuda_major | int + 1) ~ ".0a0" %} # i.e. >=11,<12.0a0

package:
  name: libcuml-split

source:
  git_url: ../../..

build:
  script_env:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - PARALLEL_LEVEL
    - CMAKE_GENERATOR
    - CMAKE_C_COMPILER_LAUNCHER
    - CMAKE_CXX_COMPILER_LAUNCHER
    - CMAKE_CUDA_COMPILER_LAUNCHER
    - SCCACHE_S3_KEY_PREFIX=libcuml-aarch64 # [aarch64]
    - SCCACHE_S3_KEY_PREFIX=libcuml-linux64 # [linux64]
    - SCCACHE_BUCKET
    - SCCACHE_REGION
    - SCCACHE_IDLE_TIMEOUT

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }} {{ cuda_version }}
    - cmake {{ cmake_version }}
    - ninja
    - sysroot_{{ target_platform }} {{ sysroot_version }}
  host:
    - cudatoolkit ={{ cuda_version }}
    - cudf ={{ minor_version }}
    - faiss-proc=*=cuda
    - gmock
    - gtest {{ gtest_version }}
    - lapack
    - libcublas {{ libcublas_host_version }}
    - libcublas-dev {{ libcublas_host_version }}
    - libcufft {{ libcufft_host_version }}
    - libcufft-dev {{ libcufft_host_version }}
    - libcumlprims ={{ minor_version }}
    - libcurand {{ libcurand_host_version }}
    - libcurand-dev {{ libcurand_host_version }}
    - libcusolver {{ libcusolver_host_version }}
    - libcusolver-dev {{ libcusolver_host_version }}
    - libcusparse {{ libcusparse_host_version }}
    - libcusparse-dev {{ libcusparse_host_version }}
    - libfaiss {{ libfaiss_version }} *_cuda
    - libraft-distance ={{ minor_version }}
    - libraft-headers ={{ minor_version }}
    - libraft-nn ={{ minor_version }}
    - treelite {{ treelite_version }}

outputs:
  - name: libcuml
    version: {{ version }}
    script: install_libcuml.sh
    build:
      number: {{ GIT_DESCRIBE_NUMBER }}
      string: cuda{{ cuda_major }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
      ignore_run_exports_from:
        - {{ compiler('cuda') }}
    requirements:
      build:
        - cmake {{ cmake_version }}
      run:
        - cudatoolkit {{ cuda_spec }}
        - cudf ={{ minor_version }}
        - faiss-proc=*=cuda
        - libcublas {{ libcublas_run_version }}
        - libcublas-dev {{ libcublas_run_version }}
        - libcufft {{ libcufft_run_version }}
        - libcumlprims ={{ minor_version }}
        - libcurand {{ libcurand_run_version }}
        - libcusparse {{ libcusparse_run_version }}
        - libcusparse-dev {{ libcusparse_run_version }}
        - libfaiss {{ libfaiss_version }} *_cuda
        - libraft-distance ={{ minor_version }}
        - libraft-headers ={{ minor_version }}
        - libraft-nn ={{ minor_version }}
        - treelite {{ treelite_version }}
    about:
      home: https://rapids.ai/
      license: Apache-2.0
      summary: libcuml library
  - name: libcuml-tests
    version: {{ version }}
    script: install_libcuml_tests.sh
    build:
      number: {{ GIT_DESCRIBE_NUMBER }}
      string: cuda{{ cuda_major }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
      ignore_run_exports_from:
        - {{ compiler('cuda') }}
    requirements:
      build:
        - cmake {{ cmake_version }}
      run:
        - cudatoolkit {{ cuda_spec }}
        - {{ pin_subpackage('libcuml', exact=True) }}
        - gtest {{ gtest_version }}
        - gmock {{ gtest_version }}
    about:
      home: https://rapids.ai/
      license: Apache-2.0
      summary: libcuml test & benchmark executables
