# Copyright (c) 2018, NVIDIA CORPORATION.

# Usage:
#   conda build . -c defaults -c conda-forge -c numba -c rapidsai -c pytorch
{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') %}
{% set git_revision_count=environ.get('GIT_DESCRIBE_NUMBER', 0) %}
{% set cuda_version='.'.join(environ.get('CUDA', '9.2').split('.')[:2]) %}
{% set cuda_major = environ.get('CUDA', '9.2').split('.')[0] %}
{% set cuda_minor = environ.get('CUDA', '9.2').split('.')[1] %}
package:
  name: libcuml
  version: {{ version }}

source:
  path: ../../..

build:
  number: {{ git_revision_count }}
  string: cuda{{ cuda_version }}_{{ git_revision_count }}
  script_env:
    - CC
    - CXX
    - CUDAHOSTCXX
    - BUILD_ABI
    - PARALLEL_LEVEL

requirements:
  build:
    - cmake>=3.14
    - cudf 0.9*
    - cudatoolkit {{ cuda_version }}.*
    - lapack
    - libclang
  run:
    - cudf 0.9*
    - {{ pin_compatible('cudatoolkit', max_pin='x.x') }}

about:
  home: http://rapids.ai/
  license: Apache-2.0
  # license_file: LICENSE
  summary: libcuml library
