# Copyright (c) 2018, NVIDIA CORPORATION.

# Usage:
#   conda build . -c defaults -c conda-forge -c nvidia -c rapidsai -c pytorch
{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version =  version.split('.')[0] + '.' + version.split('.')[1] %}
{% set git_revision_count=environ.get('GIT_DESCRIBE_NUMBER', 0) %}
{% set cuda_version='.'.join(environ.get('CUDA', '9.2').split('.')[:2]) %}
{% set cuda_major = environ.get('CUDA', '9.2').split('.')[0] %}
{% set cuda_minor = environ.get('CUDA', '9.2').split('.')[1] %}
package:
  name: libcuml
  version: {{ version }}

source:
  path: ../../..

build:
  number: {{ git_revision_count }}
  string: cuda{{ cuda_version }}_{{ git_revision_count }}
  script_env:
    - CC
    - CXX
    - CUDAHOSTCXX
    - BUILD_ABI
    - PARALLEL_LEVEL
    - VERSION_SUFFIX

requirements:
  build:
    - cmake>=3.14
    - libclang
  host:
    - nccl 2.4.*
    - cudf {{ minor_version }}
    - cudatoolkit {{ cuda_version }}.*
    - libcumlprims {{ minor_version }}
    - lapack
  run:
    - libcumlprims {{ minor_version }}
    - cudf {{ minor_version }}
    - nccl 2.4.*
    - {{ pin_compatible('cudatoolkit', max_pin='x.x') }}

about:
  home: http://rapids.ai/
  license: Apache-2.0
  # license_file: LICENSE
  summary: libcuml library
