# Copyright (c) 2018-2021, NVIDIA CORPORATION.

# Usage:
#   conda build . -c conda-forge -c nvidia -c rapidsai -c pytorch
{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version =  version.split('.')[0] + '.' + version.split('.')[1] %}
{% set cuda_version='.'.join(environ.get('CUDA', '9.2').split('.')[:2]) %}
{% set cuda_major = environ.get('CUDA', '9.2').split('.')[0] %}
{% set cuda_minor = environ.get('CUDA', '9.2').split('.')[1] %}
package:
  name: libcuml
  version: {{ version }}

source:
  git_url: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: cuda{{ cuda_version }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - CC
    - CXX
    - CUDAHOSTCXX
    - PARALLEL_LEVEL
    - VERSION_SUFFIX
    - PROJECT_FLASH
    - CCACHE_DIR
    - CCACHE_NOHASHDIR
    - CCACHE_COMPILERCHECK
    - CMAKE_GENERATOR
    - CMAKE_C_COMPILER_LAUNCHER
    - CMAKE_CXX_COMPILER_LAUNCHER
    - CMAKE_CUDA_COMPILER_LAUNCHER

requirements:
  build:
    - cmake>=3.20.1
    - clang=8.0.1        # [x86_64]
    - clang-tools=8.0.1  # [x86_64]
  host:
    - nccl>=2.9.9
    - cudf {{ minor_version }}
    - cudatoolkit {{ cuda_version }}.*
    - ucx-py 0.21
    - ucx-proc=*=gpu
    - libcumlprims {{ minor_version }}
    - lapack
    - treelite=2.0.0
    - faiss-proc=*=cuda
    - gtest=1.10.0
    - gmock
    - libfaiss 1.7.0 *cuda
  run:
    - libcumlprims {{ minor_version }}
    - cudf {{ minor_version }}
    - nccl>=2.9.9
    - ucx-py 0.21
    - ucx-proc=*=gpu
    - {{ pin_compatible('cudatoolkit', max_pin='x.x') }}
    - treelite=2.0.0
    - faiss-proc=*=cuda
    - libfaiss 1.7.0 *cuda

about:
  home: http://rapids.ai/
  license: Apache-2.0
  # license_file: LICENSE
  summary: libcuml library
