/*
 * SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION.
 * SPDX-License-Identifier: Apache-2.0
 */

#include "extratrees_rng_reference.h"

#include <cuml/ensemble/randomforest.hpp>

#include <raft/core/handle.hpp>

#include <rmm/cuda_stream_pool.hpp>

#include <thrust/device_vector.h>

#include <decisiontree/batched-levelalgo/bins.cuh>
#include <decisiontree/batched-levelalgo/kernels/builder_kernels.cuh>
#include <decisiontree/batched-levelalgo/objectives.cuh>
#include <gtest/gtest.h>

#include <algorithm>
#include <array>
#include <cmath>
#include <cstdint>
#include <limits>
#include <memory>
#include <numeric>
#include <vector>

namespace ML {
namespace DT {

// kEtRngRefTable (448 entries) is pre-generated by
// extratrees_rng_reference_gen.py; regenerate when et_split_position or
// any of its fnv1a32 / PCGenerator / UniformIntDistParams pieces change.
TEST(ExtraTreesRng, ByteIdentityVsPythonReference)
{
  for (int i = 0; i < kEtRngRefCount; ++i) {
    const auto& e = kEtRngRefTable[i];
    int got       = et_split_position<int>(e.seed, e.treeid, e.nodeid, e.col, kEtRngRefMaxNBins);
    ASSERT_EQ(got, e.expected) << "tuple #" << i << " seed=" << e.seed << " treeid=" << e.treeid
                               << " nodeid=" << e.nodeid << " col=" << e.col;
  }
}

// 10000 draws across 15 categories, chi-square at p=0.001 (df=14, exact
// critical 36.1233; we use 36.12 for a slightly more conservative threshold).
// Guards against modulo bias, wrong polynomial, or off-by-one.
TEST(ExtraTreesRng, MonteCarloUniformity)
{
  constexpr int N            = 10000;
  constexpr int max_n_bins   = 16;
  constexpr int n_categories = max_n_bins - 1;
  constexpr int n_features   = 4;
  constexpr double kChi2Crit = 36.12;

  std::vector<int> hist(n_categories, 0);
  for (int trial = 0; trial < N; ++trial) {
    uint64_t seed   = static_cast<uint64_t>(trial + 1);
    uint64_t treeid = static_cast<uint64_t>(trial * 7) % 1024u;
    uint64_t nodeid = static_cast<uint64_t>(trial * 31) % 4096u;
    uint64_t col    = static_cast<uint64_t>(trial % n_features);
    int idx         = et_split_position<int>(seed, treeid, nodeid, col, max_n_bins);
    ASSERT_GE(idx, 0);
    ASSERT_LT(idx, n_categories);
    hist[idx]++;
  }

  double mu   = static_cast<double>(N) / static_cast<double>(n_categories);
  double chi2 = 0.0;
  for (int b = 0; b < n_categories; ++b) {
    double diff = hist[b] - mu;
    chi2 += (diff * diff) / mu;
  }
  EXPECT_LT(chi2, kChi2Crit) << "chi-square = " << chi2;
}

// Spearman rank correlation with average-rank tie handling. var_a and var_b
// are non-zero for N=10000 draws over 15 categories.
static double spearman_rank_corr(const std::vector<int>& a, const std::vector<int>& b)
{
  const size_t n   = a.size();
  auto rank_vector = [n](const std::vector<int>& v) {
    std::vector<size_t> indices(n);
    std::iota(indices.begin(), indices.end(), size_t(0));
    std::sort(indices.begin(), indices.end(), [&v](size_t i, size_t j) { return v[i] < v[j]; });
    std::vector<double> ranks(n);
    size_t i = 0;
    while (i < n) {
      size_t j = i;
      while (j + 1 < n && v[indices[j + 1]] == v[indices[i]]) {
        ++j;
      }
      double avg = (static_cast<double>(i) + static_cast<double>(j)) / 2.0 + 1.0;
      for (size_t k = i; k <= j; ++k) {
        ranks[indices[k]] = avg;
      }
      i = j + 1;
    }
    return ranks;
  };
  auto ra      = rank_vector(a);
  auto rb      = rank_vector(b);
  double mean  = (static_cast<double>(n) + 1.0) / 2.0;
  double cov   = 0.0;
  double var_a = 0.0;
  double var_b = 0.0;
  for (size_t i = 0; i < n; ++i) {
    double da = ra[i] - mean;
    double db = rb[i] - mean;
    cov += da * db;
    var_a += da * da;
    var_b += db * db;
  }
  return cov / std::sqrt(var_a * var_b);
}

// At N=10000, |rho| under the null has stderr ~0.01. Bound |rho| < 0.05
// (~5 stderr from zero). Guards against the failure mode where col gets
// XOR'd into the subsequence rather than fnv1a32-chained.
TEST(ExtraTreesRng, SpearmanPairCorrelation)
{
  constexpr int N                                    = 10000;
  constexpr int max_n_bins                           = 16;
  constexpr double kRhoBound                         = 0.05;
  const std::array<std::pair<int, int>, 3> col_pairs = {{{0, 1}, {1, 2}, {2, 3}}};

  for (auto cp : col_pairs) {
    std::vector<int> a(N), b(N);
    for (int trial = 0; trial < N; ++trial) {
      uint64_t seed   = static_cast<uint64_t>(trial + 1);
      uint64_t treeid = static_cast<uint64_t>(trial * 7) % 1024u;
      uint64_t nodeid = static_cast<uint64_t>(trial * 31) % 4096u;
      a[trial] =
        et_split_position<int>(seed, treeid, nodeid, static_cast<uint64_t>(cp.first), max_n_bins);
      b[trial] =
        et_split_position<int>(seed, treeid, nodeid, static_cast<uint64_t>(cp.second), max_n_bins);
    }
    double rho = spearman_rank_corr(a, b);
    EXPECT_LT(std::abs(rho), kRhoBound)
      << "cols=(" << cp.first << "," << cp.second << ") rho=" << rho;
  }
}

// Oracle 4 covers the 24 (objective, dtype) instantiations: 5 hand-derived
// gains for representative BinT shapes plus property-based zero-gain tests
// (equal-mean for regressors, equal-class-distribution for classifiers).

TEST(ExtraTreesGain, CountBinGiniHandComputed)
{
  using DataT = float;
  using IdxT  = int;
  using ObjT  = GiniObjectiveFunction<DataT, int, IdxT>;
  using BinT  = typename ObjT::BinT;

  ObjT obj{2, 1};
  BinT left[2]   = {BinT{30}, BinT{20}};
  BinT parent[2] = {BinT{70}, BinT{30}};
  DataT gain     = obj.GainFromSideStats(left, parent);

  // Proxy Gini gain (matches GainPerSplit; nLeft=nRight=50, len=100):
  //   j=0 (30/70): (30^2 + 70^2)/(50*100) - 100^2/100^2 = 0.50 - 0.49 = 0.01
  //   j=1 (20/30): (20^2 + 30^2)/(50*100) - 50^2/100^2  = 0.26 - 0.25 = 0.01
  EXPECT_NEAR(gain, DataT(0.02), DataT(1e-5));
}

TEST(ExtraTreesGain, CountBinEntropyHandComputed)
{
  using DataT = double;
  using IdxT  = int;
  using ObjT  = EntropyObjectiveFunction<DataT, int, IdxT>;
  using BinT  = typename ObjT::BinT;

  ObjT obj{2, 1};
  BinT left[2]   = {BinT{30}, BinT{20}};
  BinT parent[2] = {BinT{70}, BinT{30}};
  DataT gain     = obj.GainFromSideStats(left, parent);

  // Proxy entropy gain. Each (lval, rval, val) triple contributes
  //   log2(lval/nLeft)*lval/len + log2(rval/nRight)*rval/len
  //   - log2(val/len)*val/len.
  // j=0 (30, 40, 70): log2(0.6)*0.3 + log2(0.8)*0.4 - log2(0.7)*0.7
  //                = -0.2210897 - 0.1287712 + 0.3602012 = 0.0103403.
  // j=1 (20, 10, 30): log2(0.4)*0.2 + log2(0.2)*0.1 - log2(0.3)*0.3
  //                = -0.2643856 - 0.2321928 + 0.5210897 = 0.0245113.
  // Total = 0.0348516.
  EXPECT_NEAR(gain, DataT(0.0348516), DataT(1e-6));
}

TEST(ExtraTreesGain, AggregateBinMSEHandComputed)
{
  using DataT = double;
  using IdxT  = int;
  using ObjT  = MSEObjectiveFunction<DataT, DataT, IdxT>;
  using BinT  = typename ObjT::BinT;

  ObjT obj{1, 1};
  BinT left[1]   = {BinT{10.0, 60}};
  BinT parent[1] = {BinT{20.0, 100}};
  DataT gain     = obj.GainFromSideStats(left, parent);

  // parent_obj = -400/100 = -4. left_obj = -100/60 = -1.6667.
  // right_lbl = 20 - 10 = 10. right_obj = -100/40 = -2.5.
  // raw = -4 - (-1.6667 + -2.5) = 0.1667. gain = 0.1667 * 0.5/100 = 8.333e-4.
  EXPECT_NEAR(gain, DataT(8.3333333333e-4), DataT(1e-10));
}

TEST(ExtraTreesGain, WeightedCountBinGiniHandComputed)
{
  using DataT = double;
  using IdxT  = int;
  using ObjT  = WeightedGiniObjectiveFunction<DataT, int, IdxT>;
  using BinT  = typename ObjT::BinT;

  ObjT obj{2, 1};
  BinT left[2]   = {BinT{60.0, 30}, BinT{20.0, 20}};
  BinT parent[2] = {BinT{140.0, 70}, BinT{30.0, 30}};
  DataT gain     = obj.GainFromSideStats(left, parent);

  // wLeft=80, wRight=90, wLen=170. For j=0 (60/140):
  //   60^2/(80*170) + 80^2/(90*170) - (140/170)^2 = 0.0048058.
  // For j=1 (20/30):
  //   20^2/(80*170) + 10^2/(90*170) - (30/170)^2 = 0.0048058.
  // Total = 0.0096117.
  EXPECT_NEAR(gain, DataT(0.009611687), DataT(1e-7));
}

TEST(ExtraTreesGain, WeightedAggregateBinMSEHandComputed)
{
  using DataT = double;
  using IdxT  = int;
  using ObjT  = WeightedMSEObjectiveFunction<DataT, DataT, IdxT>;
  using BinT  = typename ObjT::BinT;

  ObjT obj{1, 1};
  BinT left[1]   = {BinT{10.0, 80.0, 60}};
  BinT parent[1] = {BinT{20.0, 170.0, 100}};
  DataT gain     = obj.GainFromSideStats(left, parent);

  // wLeft=80, wRight=90, wLen=170. parent_obj = -400/170 = -2.3529412.
  // left_obj = -100/80 = -1.25. right_lbl = 10. right_obj = -100/90 = -1.1111111.
  // raw = -2.3529412 - (-1.25 + -1.1111111) = 0.008169934. gain = 0.008169934 *
  //   0.5/170 = 5/(612*340) = 2.402921953e-5.
  EXPECT_NEAR(gain, DataT(2.402921953e-5), DataT(1e-12));
}

// Equal-mean property: variance-style regressor objectives give gain=0 when
// left and right share the parent's label_sum/count ratio. Tolerance is
// dtype-relative to absorb float32 residual from intermediate ops.
template <typename ObjT, typename BinT>
static void equal_mean_regressor_zero_gain()
{
  using DataT = typename ObjT::DataT;
  ObjT obj{1, 1};
  BinT left[1];
  BinT parent[1];
  if constexpr (std::is_same_v<BinT, AggregateBin>) {
    left[0]   = BinT{6.0, 60};
    parent[0] = BinT{10.0, 100};
  } else {
    left[0]   = BinT{6.0, 60.0, 60};
    parent[0] = BinT{10.0, 100.0, 100};
  }
  DataT gain    = obj.GainFromSideStats(left, parent);
  DataT eps_tol = DataT(100) * std::numeric_limits<DataT>::epsilon();
  EXPECT_NEAR(gain, DataT(0.0), eps_tol) << "Equal-mean split should give zero gain; got " << gain;
  // Also assert the helper did not hit a sentinel-return branch.
  EXPECT_GT(gain, -std::numeric_limits<DataT>::max() / DataT(2));
}

// Equal-class-distribution property: classifier split where left and right
// share the parent's class-frequency ratio gives gain=0.
template <typename ObjT, typename BinT>
static void equal_mean_classifier_zero_gain()
{
  using DataT = typename ObjT::DataT;
  ObjT obj{2, 1};
  BinT left[2];
  BinT parent[2];
  if constexpr (std::is_same_v<BinT, CountBin>) {
    left[0]   = BinT{30};
    left[1]   = BinT{20};
    parent[0] = BinT{60};
    parent[1] = BinT{40};
  } else {
    left[0]   = BinT{30.0, 30};
    left[1]   = BinT{20.0, 20};
    parent[0] = BinT{60.0, 60};
    parent[1] = BinT{40.0, 40};
  }
  DataT gain    = obj.GainFromSideStats(left, parent);
  DataT eps_tol = DataT(100) * std::numeric_limits<DataT>::epsilon();
  EXPECT_NEAR(gain, DataT(0.0), eps_tol)
    << "Equal-class-distribution split should give zero gain; got " << gain;
  EXPECT_GT(gain, -std::numeric_limits<DataT>::max() / DataT(2));
}

// Cover all 24 (objective, dtype) instantiations via a known property.
TEST(ExtraTreesGain, EqualMeanRegressorsZeroGain)
{
  equal_mean_regressor_zero_gain<MSEObjectiveFunction<float, float, int>, AggregateBin>();
  equal_mean_regressor_zero_gain<MSEObjectiveFunction<double, double, int>, AggregateBin>();
  equal_mean_regressor_zero_gain<PoissonObjectiveFunction<float, float, int>, AggregateBin>();
  equal_mean_regressor_zero_gain<PoissonObjectiveFunction<double, double, int>, AggregateBin>();
  equal_mean_regressor_zero_gain<GammaObjectiveFunction<float, float, int>, AggregateBin>();
  equal_mean_regressor_zero_gain<GammaObjectiveFunction<double, double, int>, AggregateBin>();
  equal_mean_regressor_zero_gain<InverseGaussianObjectiveFunction<float, float, int>,
                                 AggregateBin>();
  equal_mean_regressor_zero_gain<InverseGaussianObjectiveFunction<double, double, int>,
                                 AggregateBin>();
  equal_mean_regressor_zero_gain<WeightedMSEObjectiveFunction<float, float, int>,
                                 WeightedAggregateBin>();
  equal_mean_regressor_zero_gain<WeightedMSEObjectiveFunction<double, double, int>,
                                 WeightedAggregateBin>();
  equal_mean_regressor_zero_gain<WeightedPoissonObjectiveFunction<float, float, int>,
                                 WeightedAggregateBin>();
  equal_mean_regressor_zero_gain<WeightedPoissonObjectiveFunction<double, double, int>,
                                 WeightedAggregateBin>();
  equal_mean_regressor_zero_gain<WeightedGammaObjectiveFunction<float, float, int>,
                                 WeightedAggregateBin>();
  equal_mean_regressor_zero_gain<WeightedGammaObjectiveFunction<double, double, int>,
                                 WeightedAggregateBin>();
  equal_mean_regressor_zero_gain<WeightedInverseGaussianObjectiveFunction<float, float, int>,
                                 WeightedAggregateBin>();
  equal_mean_regressor_zero_gain<WeightedInverseGaussianObjectiveFunction<double, double, int>,
                                 WeightedAggregateBin>();
}

TEST(ExtraTreesGain, EqualClassDistributionClassifiersZeroGain)
{
  equal_mean_classifier_zero_gain<GiniObjectiveFunction<float, int, int>, CountBin>();
  equal_mean_classifier_zero_gain<GiniObjectiveFunction<double, int, int>, CountBin>();
  equal_mean_classifier_zero_gain<EntropyObjectiveFunction<float, int, int>, CountBin>();
  equal_mean_classifier_zero_gain<EntropyObjectiveFunction<double, int, int>, CountBin>();
  equal_mean_classifier_zero_gain<WeightedGiniObjectiveFunction<float, int, int>,
                                  WeightedCountBin>();
  equal_mean_classifier_zero_gain<WeightedGiniObjectiveFunction<double, int, int>,
                                  WeightedCountBin>();
  equal_mean_classifier_zero_gain<WeightedEntropyObjectiveFunction<float, int, int>,
                                  WeightedCountBin>();
  equal_mean_classifier_zero_gain<WeightedEntropyObjectiveFunction<double, int, int>,
                                  WeightedCountBin>();
}

// End-to-end smoke: fit a single tree with SPLITTER_RANDOM on a small
// linearly separable classifier dataset; expect a non-trivial split.
TEST(ExtraTreesFit, SingleTreeClassifierSmoke)
{
  using DataT  = float;
  using LabelT = int;

  // 12 rows, one feature: classes are linearly separable around X=3.5.
  std::vector<DataT> X_host  = {1, 2, 3, 3, 3, 4, 4, 5, 6, 7, 8, 9};
  std::vector<LabelT> y_host = {0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1};
  int n_rows                 = static_cast<int>(X_host.size());
  int n_cols                 = 1;
  int n_classes              = 2;

  thrust::device_vector<DataT> X  = X_host;
  thrust::device_vector<LabelT> y = y_host;

  RF_params rf_params = set_rf_params(/*max_depth*/ 3,
                                      /*max_leaves*/ -1,
                                      /*max_features*/ 1.0f,
                                      /*max_n_bins*/ 8,
                                      /*min_samples_leaf*/ 1,
                                      /*min_samples_split*/ 2,
                                      /*min_impurity_decrease*/ 0.0f,
                                      /*bootstrap*/ false,
                                      /*n_trees*/ 1,
                                      /*max_samples*/ 1.0f,
                                      /*seed*/ 42,
                                      /*split_criterion*/ GINI,
                                      /*n_streams*/ 1,
                                      /*max_batch_size*/ 128,
                                      /*cfg_splitter*/ DT::SPLITTER_RANDOM);

  auto forest      = std::make_shared<RandomForestMetaData<DataT, LabelT>>();
  auto stream_pool = std::make_shared<rmm::cuda_stream_pool>(1);
  raft::handle_t handle(rmm::cuda_stream_per_thread, stream_pool);

  fit(handle, forest.get(), X.data().get(), n_rows, n_cols, y.data().get(), n_classes, rf_params);

  // The fit must produce at least one tree with a non-trivial structure.
  ASSERT_EQ(forest->trees.size(), size_t(1));
  EXPECT_GE(forest->trees[0]->sparsetree.size(), size_t(3))
    << "ET tree should produce at least one split node + two leaves";
  EXPECT_GE(forest->trees[0]->depth_counter, 1);
}

// Regressor counterpart: exercises the AggregateBin / MSE end-to-end path
// (smem layout, memset extent and reduction shape differ from CountBin).
TEST(ExtraTreesFit, SingleTreeRegressorSmoke)
{
  using DataT  = float;
  using LabelT = float;

  std::vector<DataT> X_host  = {1, 2, 3, 3, 3, 4, 4, 5, 6, 7, 8, 9};
  std::vector<LabelT> y_host = {0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1};
  int n_rows                 = static_cast<int>(X_host.size());
  int n_cols                 = 1;

  thrust::device_vector<DataT> X  = X_host;
  thrust::device_vector<LabelT> y = y_host;

  RF_params rf_params = set_rf_params(/*max_depth*/ 3,
                                      /*max_leaves*/ -1,
                                      /*max_features*/ 1.0f,
                                      /*max_n_bins*/ 8,
                                      /*min_samples_leaf*/ 1,
                                      /*min_samples_split*/ 2,
                                      /*min_impurity_decrease*/ 0.0f,
                                      /*bootstrap*/ false,
                                      /*n_trees*/ 1,
                                      /*max_samples*/ 1.0f,
                                      /*seed*/ 42,
                                      /*split_criterion*/ MSE,
                                      /*n_streams*/ 1,
                                      /*max_batch_size*/ 128,
                                      /*cfg_splitter*/ DT::SPLITTER_RANDOM);

  auto forest      = std::make_shared<RandomForestMetaData<DataT, LabelT>>();
  auto stream_pool = std::make_shared<rmm::cuda_stream_pool>(1);
  raft::handle_t handle(rmm::cuda_stream_per_thread, stream_pool);

  fit(handle, forest.get(), X.data().get(), n_rows, n_cols, y.data().get(), rf_params);

  ASSERT_EQ(forest->trees.size(), size_t(1));
  EXPECT_GE(forest->trees[0]->sparsetree.size(), size_t(3));
  EXPECT_GE(forest->trees[0]->depth_counter, 1);
}

// Constant column has n_bins_array[col] == 1; et_split_position's Lemire
// chain is undefined there. The kernel must skip the column and let the
// varying one win without crashing.
TEST(ExtraTreesFit, ConstantFeatureColumn)
{
  using DataT  = float;
  using LabelT = int;

  std::vector<DataT> X_host = {
    1, 2, 3, 3, 3, 4, 4, 5, 6, 7, 8, 9,  // column 0 (varying)
    7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,  // column 1 (constant)
  };
  std::vector<LabelT> y_host = {0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1};
  int n_rows                 = 12;
  int n_cols                 = 2;
  int n_classes              = 2;

  thrust::device_vector<DataT> X  = X_host;
  thrust::device_vector<LabelT> y = y_host;

  RF_params rf_params = set_rf_params(/*max_depth*/ 3,
                                      /*max_leaves*/ -1,
                                      /*max_features*/ 1.0f,
                                      /*max_n_bins*/ 8,
                                      /*min_samples_leaf*/ 1,
                                      /*min_samples_split*/ 2,
                                      /*min_impurity_decrease*/ 0.0f,
                                      /*bootstrap*/ false,
                                      /*n_trees*/ 1,
                                      /*max_samples*/ 1.0f,
                                      /*seed*/ 42,
                                      /*split_criterion*/ GINI,
                                      /*n_streams*/ 1,
                                      /*max_batch_size*/ 128,
                                      /*cfg_splitter*/ DT::SPLITTER_RANDOM);

  auto forest      = std::make_shared<RandomForestMetaData<DataT, LabelT>>();
  auto stream_pool = std::make_shared<rmm::cuda_stream_pool>(1);
  raft::handle_t handle(rmm::cuda_stream_per_thread, stream_pool);

  fit(handle, forest.get(), X.data().get(), n_rows, n_cols, y.data().get(), n_classes, rf_params);

  ASSERT_EQ(forest->trees.size(), size_t(1));
  EXPECT_GE(forest->trees[0]->sparsetree.size(), size_t(3));
  EXPECT_GE(forest->trees[0]->depth_counter, 1);
  for (const auto& node : forest->trees[0]->sparsetree) {
    if (node.IsLeaf()) continue;
    EXPECT_EQ(node.ColumnId(), 0)
      << "split landed on the constant column; n_bins<2 guard failed";
  }
}

// Regressor sibling: the n_bins<2 guard fires before any BinT-specific work,
// so it must hold for AggregateBin (MSE) as well as CountBin (Gini).
TEST(ExtraTreesFit, ConstantFeatureColumnRegressor)
{
  using DataT  = float;
  using LabelT = float;

  std::vector<DataT> X_host = {
    1, 2, 3, 3, 3, 4, 4, 5, 6, 7, 8, 9,
    7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
  };
  std::vector<LabelT> y_host = {0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1};
  int n_rows                 = 12;
  int n_cols                 = 2;

  thrust::device_vector<DataT> X  = X_host;
  thrust::device_vector<LabelT> y = y_host;

  RF_params rf_params = set_rf_params(/*max_depth*/ 3,
                                      /*max_leaves*/ -1,
                                      /*max_features*/ 1.0f,
                                      /*max_n_bins*/ 8,
                                      /*min_samples_leaf*/ 1,
                                      /*min_samples_split*/ 2,
                                      /*min_impurity_decrease*/ 0.0f,
                                      /*bootstrap*/ false,
                                      /*n_trees*/ 1,
                                      /*max_samples*/ 1.0f,
                                      /*seed*/ 42,
                                      /*split_criterion*/ MSE,
                                      /*n_streams*/ 1,
                                      /*max_batch_size*/ 128,
                                      /*cfg_splitter*/ DT::SPLITTER_RANDOM);

  auto forest      = std::make_shared<RandomForestMetaData<DataT, LabelT>>();
  auto stream_pool = std::make_shared<rmm::cuda_stream_pool>(1);
  raft::handle_t handle(rmm::cuda_stream_per_thread, stream_pool);

  fit(handle, forest.get(), X.data().get(), n_rows, n_cols, y.data().get(), rf_params);

  ASSERT_EQ(forest->trees.size(), size_t(1));
  EXPECT_GE(forest->trees[0]->sparsetree.size(), size_t(3));
  EXPECT_GE(forest->trees[0]->depth_counter, 1);
  for (const auto& node : forest->trees[0]->sparsetree) {
    if (node.IsLeaf()) continue;
    EXPECT_EQ(node.ColumnId(), 0)
      << "split landed on the constant column; n_bins<2 guard failed";
  }
}

// Every feature constant: every block early-returns, signalDone is never
// reached, and the root stays a leaf with no valid split.
TEST(ExtraTreesFit, AllConstantFeatureColumns)
{
  using DataT  = float;
  using LabelT = int;

  std::vector<DataT> X_host = {
    5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
    7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
  };
  std::vector<LabelT> y_host = {0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1};
  int n_rows                 = 12;
  int n_cols                 = 2;
  int n_classes              = 2;

  thrust::device_vector<DataT> X  = X_host;
  thrust::device_vector<LabelT> y = y_host;

  RF_params rf_params = set_rf_params(/*max_depth*/ 3,
                                      /*max_leaves*/ -1,
                                      /*max_features*/ 1.0f,
                                      /*max_n_bins*/ 8,
                                      /*min_samples_leaf*/ 1,
                                      /*min_samples_split*/ 2,
                                      /*min_impurity_decrease*/ 0.0f,
                                      /*bootstrap*/ false,
                                      /*n_trees*/ 1,
                                      /*max_samples*/ 1.0f,
                                      /*seed*/ 42,
                                      /*split_criterion*/ GINI,
                                      /*n_streams*/ 1,
                                      /*max_batch_size*/ 128,
                                      /*cfg_splitter*/ DT::SPLITTER_RANDOM);

  auto forest      = std::make_shared<RandomForestMetaData<DataT, LabelT>>();
  auto stream_pool = std::make_shared<rmm::cuda_stream_pool>(1);
  raft::handle_t handle(rmm::cuda_stream_per_thread, stream_pool);

  fit(handle, forest.get(), X.data().get(), n_rows, n_cols, y.data().get(), n_classes, rf_params);

  ASSERT_EQ(forest->trees.size(), size_t(1));
  EXPECT_EQ(forest->trees[0]->sparsetree.size(), size_t(1));
  EXPECT_TRUE(forest->trees[0]->sparsetree[0].IsLeaf());
  EXPECT_EQ(forest->trees[0]->depth_counter, 0);
}

}  // namespace DT
}  // namespace ML
