#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0
"""Generate extratrees_rng_reference.h.

Bit-for-bit port of raft::random::PCGenerator + UniformIntDistParams (Lemire
bounded integer) plus the 3-term fnv1a32 chain used by the ExtraTrees
et_split_position helper. Emits a C++ header containing a constexpr table of
expected (seed, treeid, nodeid, col) -> bin_index entries the gtest asserts
against.

The emitted header is checked in alongside this script. Regenerate via:
    python extratrees_rng_reference_gen.py extratrees_rng_reference.h
whenever et_split_position, the underlying RAFT PCGenerator or UniformIntDist
helpers, or the fnv1a32 chain change.
"""

import sys

_U32 = 0xFFFFFFFF
_U64 = 0xFFFFFFFFFFFFFFFF
_FNV_PRIME = 16777619
_FNV_BASIS = 2166136261
_PCG_MUL = 6364136223846793005


def fnv1a32(h, txt):
    h = ((h ^ (txt & 0xFF)) * _FNV_PRIME) & _U32
    h = ((h ^ ((txt >> 8) & 0xFF)) * _FNV_PRIME) & _U32
    h = ((h ^ ((txt >> 16) & 0xFF)) * _FNV_PRIME) & _U32
    h = ((h ^ ((txt >> 24) & 0xFF)) * _FNV_PRIME) & _U32
    return h


class PCGenerator:
    """Bit-for-bit port of raft::random::PCGenerator from
    raft/random/detail/rng_device.cuh (PCGenerator + _init_pcg)."""

    def __init__(self, seed, subsequence, offset):
        # _init_pcg: state = 0; inc = (subsequence << 1) | 1;
        #            next(discard); state += seed; next(discard); skipahead(offset)
        self.state = 0
        self.inc = ((subsequence << 1) | 1) & _U64
        self.next_u32()
        self.state = (self.state + seed) & _U64
        self.next_u32()
        assert offset == 0, "non-zero offset path not exercised by ET kernel"

    def next_u32(self):
        oldstate = self.state
        self.state = (oldstate * _PCG_MUL + self.inc) & _U64
        xorshifted = (((oldstate >> 18) ^ oldstate) >> 27) & _U32
        rot = (oldstate >> 59) & 0x1F
        ret = ((xorshifted >> rot) | (xorshifted << ((-rot) & 31))) & _U32
        return ret

    def next_u64(self):
        a = self.next_u32()
        b = self.next_u32()
        return (a | (b << 32)) & _U64


def uniform_int_u64(gen, diff):
    """Bit-for-bit port of raft::random::custom_next for
    UniformIntDistParams<OutType, uint64_t>. Lemire's bias-free bounded
    integer with rejection on the low 64 bits."""
    s = diff & _U64
    x = gen.next_u64()
    prod = x * s
    m_hi = (prod >> 64) & _U64
    m_lo = prod & _U64
    if m_lo < s:
        t = ((-s) & _U64) % s
        while m_lo < t:
            x = gen.next_u64()
            prod = x * s
            m_hi = (prod >> 64) & _U64
            m_lo = prod & _U64
    return m_hi  # since params.start = 0


def et_split_position_reference(seed, treeid, nodeid, col, max_n_bins):
    subsequence = _FNV_BASIS
    subsequence = fnv1a32(subsequence, treeid & _U32)
    subsequence = fnv1a32(subsequence, nodeid & _U32)
    subsequence = fnv1a32(subsequence, col & _U32)
    gen = PCGenerator(seed & _U64, subsequence & _U64, 0)
    return uniform_int_u64(gen, max_n_bins - 1)


# Oracle 1 test matrix: 7 * 4 * 4 * 4 = 448 tuples.
# seed=0 covers the production-default sentinel case (random_state=None
# translates to seed=0 at the C++ layer).
SEEDS = (0, 1, 42, 1337, 314159, 271828, 2718281)
TREEIDS = (0, 1, 7, 99)
NODEIDS = (0, 1, 16, 255)
COLS = (0, 1, 2, 3)
MAX_N_BINS = 16


def emit_header(out_path):
    entries = []
    for s in SEEDS:
        for t in TREEIDS:
            for n in NODEIDS:
                for c in COLS:
                    idx = et_split_position_reference(s, t, n, c, MAX_N_BINS)
                    entries.append((s, t, n, c, idx))

    with open(out_path, "w") as f:
        f.write(
            "/*\n"
            " * SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION.\n"
            " * SPDX-License-Identifier: Apache-2.0\n"
            " *\n"
            " * Auto-generated by extratrees_rng_reference_gen.py. Do not edit.\n"
            " * Encodes the (seed, treeid, nodeid, col) -> bin_index byte-identity\n"
            " * table the ExtraTrees Oracle 1 gtest asserts against.\n"
            " */\n"
            "#pragma once\n\n"
            "#include <cstdint>\n\n"
            "namespace ML {\n"
            "namespace DT {\n\n"
            "struct EtRngRefEntry {\n"
            "  uint64_t seed;\n"
            "  uint64_t treeid;\n"
            "  uint64_t nodeid;\n"
            "  uint64_t col;\n"
            "  int      expected;\n"
            "};\n\n"
            f"constexpr int kEtRngRefMaxNBins = {MAX_N_BINS};\n"
            f"constexpr int kEtRngRefCount   = {len(entries)};\n\n"
            "constexpr EtRngRefEntry kEtRngRefTable[] = {\n"
        )
        for s, t, n, c, idx in entries:
            f.write(f"  {{ {s}ull, {t}ull, {n}ull, {c}ull, {idx} }},\n")
        f.write("};\n\n}  // namespace DT\n}  // namespace ML\n")


if __name__ == "__main__":
    out_path = (
        sys.argv[1] if len(sys.argv) > 1 else "extratrees_rng_reference.h"
    )
    emit_header(out_path)
    print(f"wrote {out_path}")
