c_compiler_version:
  - 13  # [not os.environ.get("RAPIDS_CUDA_VERSION", "").startswith("11")]
  - 11  # [os.environ.get("RAPIDS_CUDA_VERSION", "").startswith("11")]

cxx_compiler_version:
  - 13  # [not os.environ.get("RAPIDS_CUDA_VERSION", "").startswith("11")]
  - 11  # [os.environ.get("RAPIDS_CUDA_VERSION", "").startswith("11")]

cmake_version:
  - ">=3.30.4"

c_stdlib:
  - sysroot

c_stdlib_version:
  - "=2.28"
