# Copyright (c) 2023-2025, NVIDIA CORPORATION.

{% set version = environ['RAPIDS_PACKAGE_VERSION'].lstrip('v')  + environ.get('VERSION_SUFFIX', '') %}
{% set py_version = environ['CONDA_PY'] %}
{% set date_string = environ['RAPIDS_DATE_STRING'] %}

package:
  name: cuml-cpu
  version: {{ version }}

source:
  path: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: py{{ py_version }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - VERSION_SUFFIX

requirements:
  build:
    - cmake {{ cmake_version }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - ninja
  host:
    - python x.x
    - scikit-build-core >=0.10.0
    - cython>=3.0.0
    - rapids-build-backend>=0.3.0,<0.4.0.dev0
  run:
    - python x.x
    - numpy>=1.23,<3.0a0
    - pandas
    - packaging
    - scikit-learn==1.5.*
    - hdbscan>=0.8.39,<0.8.40
    - umap-learn=0.5.6
    - nvtx

test:
  # test that the package is installable and these modules are importable
  imports:
    - cuml

about:
  home: https://rapids.ai/
  license: Apache-2.0
  license_file: LICENSE
  summary: cuML-CPU library
