# Copyright (c) 2023, NVIDIA CORPORATION.

# Usage:
#   conda build . -c conda-forge -c numba -c rapidsai -c pytorch
# {% set version = 23.10 %}
# {% set py_version = 3.10 %}
# {% set date_string = 0101 %}

package:
  name: cuml-cpu
  version: 23.10
  script: build_cuml_cpu.sh

source:
  git_url: ../../..

build:
  number: 12
  string: py3.10
  script_env:
    - VERSION_SUFFIX

requirements:
  build:
    - cmake {{ cmake_version }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - sysroot_{{ target_platform }} {{ sysroot_version }}
    - ninja
  host:
    - python x.x
    - setuptools
    - scikit-build>=0.13.1
    - cython>=3.0.0
  run:
    - python x.x
    - numpy
    - scikit-learn=1.2
    - hdbscan<=0.8.30
    - umap-learn=0.5.3
    - nvtx

# tests:                                 # [linux64]
#   imports:                             # [linux64]
#     - cuml-cpu                         # [linux64]

about:
  home: http://rapids.ai/
  license: Apache-2.0
  # license_file: LICENSE
  summary: cuML-CPU library
