# Copyright (c) 2025, NVIDIA CORPORATION.
schema_version: 1

context:
  version: ${{ env.get("RAPIDS_PACKAGE_VERSION") }}
  date_string: '${{ env.get("RAPIDS_DATE_STRING") }}'
  py_version: ${{ env.get("RAPIDS_PY_VERSION") }}
  py_buildstring: ${{ py_version | version_to_buildstring }}
  head_rev: ${{ git.head_rev(".")[:8] }}

package:
  name: cuml-cpu
  version: ${{ version }}

source:
  path: ../../..

build:
  string: py${{ py_buildstring }}_${{ date_string }}_${{ head_rev }}
  dynamic_linking:
    overlinking_behavior: "error"
  script:
    content: |
      ./build.sh cuml-cpu -v
    secrets:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
    env:
      CMAKE_C_COMPILER_LAUNCHER: ${{ env.get("CMAKE_C_COMPILER_LAUNCHER") }}
      CMAKE_CXX_COMPILER_LAUNCHER: ${{ env.get("CMAKE_CXX_COMPILER_LAUNCHER") }}
      CMAKE_GENERATOR: ${{ env.get("CMAKE_GENERATOR") }}
      SCCACHE_BUCKET: ${{ env.get("SCCACHE_BUCKET") }}
      SCCACHE_IDLE_TIMEOUT: ${{ env.get("SCCACHE_IDLE_TIMEOUT") }}
      SCCACHE_REGION: ${{ env.get("SCCACHE_REGION") }}
      SCCACHE_S3_USE_SSL: ${{ env.get("SCCACHE_S3_USE_SSL") }}
      SCCACHE_S3_NO_CREDENTIALS: ${{ env.get("SCCACHE_S3_NO_CREDENTIALS") }}
      SCCACHE_S3_KEY_PREFIX: cuml-cpu/${{ env.get("RAPIDS_CONDA_ARCH") }}

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - cmake ${{ cmake_version }}
    - ninja
  host:
    - cython >=3.0.0
    - pip
    - python =${{ py_version }}
    - rapids-build-backend>=0.3.0,<0.4.0.dev0
    - scikit-build-core >=0.10.0
  run:
    - numpy >=1.23,<3.0a0
    - python
    - pandas
    - packaging
    - scikit-learn 1.5.*
    - hdbscan>=0.8.39,<0.8.40
    - umap-learn=0.5.6
    - nvtx
  ignore_run_exports:
    by_name:
      - cuda-cudart
      - cuda-version
      - if: cuda_major == "11"
        then: cudatoolkit

tests:
  - python:
      imports:
        - cuml
      pip_check: false

about:
  homepage: ${{ load_from_file("python/cuml/pyproject.toml").project.urls.Homepage }}
  license: ${{ load_from_file("python/cuml/pyproject.toml").project.license.text }}
  summary: cuML-CPU Library
