#
# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0
#
from functools import partial

import pytest
from sklearn.utils import estimator_checks

from cuml.cluster import DBSCAN, HDBSCAN, AgglomerativeClustering, KMeans
from cuml.covariance import LedoitWolf
from cuml.decomposition import PCA, IncrementalPCA, TruncatedSVD
from cuml.ensemble import RandomForestClassifier, RandomForestRegressor
from cuml.kernel_ridge import KernelRidge
from cuml.linear_model import (
    ElasticNet,
    Lasso,
    LinearRegression,
    LogisticRegression,
    Ridge,
)
from cuml.manifold import TSNE, UMAP
from cuml.naive_bayes import (
    BernoulliNB,
    CategoricalNB,
    ComplementNB,
    GaussianNB,
    MultinomialNB,
)
from cuml.neighbors import (
    KernelDensity,
    KNeighborsClassifier,
    KNeighborsRegressor,
    NearestNeighbors,
)
from cuml.random_projection import (
    GaussianRandomProjection,
    SparseRandomProjection,
)
from cuml.svm import SVC, SVR, LinearSVC, LinearSVR

# Skip these tests as parameterize_with_checks does not support
# strict_xfail in older versions of scikit-learn.
pytest.importorskip("sklearn", minversion="1.8")


PER_ESTIMATOR_XFAIL_CHECKS = {
    KMeans: {
        "check_estimator_tags_renamed": "No support for modern tags infrastructure",
        "check_sample_weights_not_an_array": "KMeans does not handle non-array sample weights",
        "check_sample_weights_list": "KMeans does not handle list sample weights",
        "check_sample_weight_equivalence_on_dense_data": "KMeans sample weight equivalence not implemented",
        "check_all_zero_sample_weights_error": "KMeans does not validate all-zero sample weights",
        "check_dtype_object": "KMeans does not handle object dtype",
        "check_estimators_nan_inf": "KMeans does not check for NaN and inf",
        "check_transformer_data_not_an_array": "KMeans does not handle non-array data",
    },
    KernelRidge: {
        "check_estimator_tags_renamed": "No support for modern tags infrastructure",
        "check_sample_weights_not_an_array": "KernelRidge does not handle non-array sample weights",
        "check_all_zero_sample_weights_error": "KernelRidge does not validate all-zero sample weights",
        "check_dtype_object": "KernelRidge does not handle object dtype",
        "check_estimators_empty_data_messages": "KernelRidge does not handle empty data",
        "check_estimators_nan_inf": "KernelRidge does not check for NaN and inf",
        "check_regressors_train": "KernelRidge does not handle list inputs",
        "check_regressors_train(readonly_memmap=True)": "KernelRidge does not handle readonly memmap",
        "check_regressors_train(readonly_memmap=True,X_dtype=float32)": "KernelRidge does not handle readonly memmap with float32",
        "check_regressor_data_not_an_array": "KernelRidge does not handle non-array data",
        "check_supervised_y_2d": "KernelRidge does not handle 2D y",
        "check_supervised_y_no_nan": "KernelRidge does not check for NaN in y",
    },
    LogisticRegression: {
        "check_estimator_tags_renamed": "No support for modern tags infrastructure",
        "check_estimators_unfitted": "LogisticRegression does not raise NotFittedError before fit",
        "check_sample_weights_not_an_array": "LogisticRegression does not handle non-array sample weights",
        "check_sample_weights_list": "LogisticRegression does not handle list sample weights",
        "check_sample_weight_equivalence_on_dense_data": "LogisticRegression sample weight equivalence not implemented",
        "check_sample_weight_equivalence_on_sparse_data": "LogisticRegression does not handle sparse data",
        "check_all_zero_sample_weights_error": "LogisticRegression does not validate all-zero sample weights",
        "check_dtype_object": "LogisticRegression does not handle object dtype",
        "check_estimators_empty_data_messages": "LogisticRegression does not handle empty data",
        "check_estimators_nan_inf": "LogisticRegression does not check for NaN and inf",
        "check_classifier_data_not_an_array": "LogisticRegression does not handle non-array data",
        "check_classifiers_train": "LogisticRegression does not handle list inputs",
        "check_classifiers_train(readonly_memmap=True)": "LogisticRegression does not handle readonly memmap",
        "check_classifiers_train(readonly_memmap=True,X_dtype=float32)": "LogisticRegression does not handle readonly memmap with float32",
        "check_supervised_y_2d": "LogisticRegression does not handle 2D y",
        "check_class_weight_classifiers": "LogisticRegression does not handle class weights properly",
        "check_fit2d_1sample": "LogisticRegression does not handle single sample",
    },
    LinearRegression: {
        "check_estimator_tags_renamed": "No support for modern tags infrastructure",
        "check_sample_weights_not_an_array": "LinearRegression does not handle non-array sample weights",
        "check_sample_weights_list": "LinearRegression does not handle list sample weights",
        "check_all_zero_sample_weights_error": "LinearRegression does not validate all-zero sample weights",
        "check_dtype_object": "LinearRegression does not handle object dtype",
        "check_estimators_empty_data_messages": "LinearRegression does not handle empty data",
        "check_estimators_nan_inf": "LinearRegression does not check for NaN and inf",
        "check_regressors_train": "LinearRegression does not handle list inputs",
        "check_regressors_train(readonly_memmap=True)": "LinearRegression does not handle readonly memmap",
        "check_regressors_train(readonly_memmap=True,X_dtype=float32)": "LinearRegression does not handle readonly memmap with float32",
        "check_regressor_data_not_an_array": "LinearRegression does not handle non-array data",
        "check_supervised_y_no_nan": "LinearRegression does not check for NaN in y",
        "check_fit2d_1sample": "LinearRegression does not handle single sample",
    },
    Ridge: {
        "check_estimator_tags_renamed": "No support for modern tags infrastructure",
        "check_sample_weights_not_an_array": "Ridge does not handle non-array sample weights",
        "check_sample_weights_list": "Ridge does not handle list sample weights",
        "check_all_zero_sample_weights_error": "Ridge does not validate all-zero sample weights",
        "check_dtype_object": "Ridge does not handle object dtype",
        "check_estimators_nan_inf": "Ridge does not check for NaN and inf",
        "check_regressors_train": "Ridge does not handle list inputs",
        "check_regressors_train(readonly_memmap=True)": "Ridge does not handle readonly memmap",
        "check_regressors_train(readonly_memmap=True,X_dtype=float32)": "Ridge does not handle readonly memmap with float32",
        "check_regressor_data_not_an_array": "Ridge does not handle non-array data",
        "check_supervised_y_2d": "Ridge does not handle 2D y",
        "check_supervised_y_no_nan": "Ridge does not check for NaN in y",
    },
    RandomForestRegressor: {
        "check_estimator_tags_renamed": "No support for modern tags infrastructure",
        "check_do_not_raise_errors_in_init_or_set_params": "RandomForestRegressor raises errors in init or set_params",
        "check_n_features_in_after_fitting": "RandomForestRegressor does not check n_features_in consistency",
        "check_dtype_object": "RandomForestRegressor does not handle object dtype",
        "check_estimators_empty_data_messages": "RandomForestRegressor does not handle empty data",
        "check_estimators_nan_inf": "RandomForestRegressor does not check for NaN and inf",
        "check_regressors_train": "RandomForestRegressor does not handle list inputs",
        "check_regressors_train(readonly_memmap=True)": "RandomForestRegressor does not handle readonly memmap",
        "check_regressors_train(readonly_memmap=True,X_dtype=float32)": "RandomForestRegressor does not handle readonly memmap with float32",
        "check_regressor_data_not_an_array": "RandomForestRegressor does not handle non-array data",
        "check_supervised_y_2d": "RandomForestRegressor does not handle 2D y",
        "check_supervised_y_no_nan": "RandomForestRegressor does not check for NaN in y",
        "check_dict_unchanged": "RandomForestRegressor modifies input dictionaries",
    },
    KNeighborsClassifier: {
        "check_estimator_tags_renamed": "No support for modern tags infrastructure",
        "check_no_attributes_set_in_init": "KNeighborsClassifier sets attributes during init",
        "check_estimators_unfitted": "KNeighborsClassifier does not raise NotFittedError before fit",
        "check_do_not_raise_errors_in_init_or_set_params": "KNeighborsClassifier raises errors in init or set_params",
        "check_n_features_in_after_fitting": "KNeighborsClassifier does not check n_features_in consistency",
        "check_dtype_object": "KNeighborsClassifier does not handle object dtype",
        "check_estimators_empty_data_messages": "KNeighborsClassifier does not handle empty data",
        "check_estimators_nan_inf": "KNeighborsClassifier does not check for NaN and inf",
        "check_classifier_data_not_an_array": "KNeighborsClassifier does not handle non-array data",
        "check_classifiers_train": "KNeighborsClassifier does not validate input data properly",
        "check_supervised_y_no_nan": "KNeighborsClassifier does not check for NaN in y",
        "check_supervised_y_2d": "KNeighborsClassifier does not handle 2D y",
        "check_fit_check_is_fitted": "KNeighborsClassifier passes check_is_fitted before being fit",
        "check_fit2d_predict1d": "KNeighborsClassifier does not handle 1D prediction input gracefully",
    },
    RandomForestClassifier: {
        "check_estimator_tags_renamed": "No support for modern tags infrastructure",
        "check_estimators_unfitted": "RandomForestClassifier does not raise NotFittedError before fit",
        "check_do_not_raise_errors_in_init_or_set_params": "RandomForestClassifier raises errors in init or set_params",
        "check_n_features_in_after_fitting": "RandomForestClassifier does not check n_features_in consistency",
        "check_dtype_object": "RandomForestClassifier does not handle object dtype",
        "check_estimators_empty_data_messages": "RandomForestClassifier does not handle empty data",
        "check_estimators_nan_inf": "RandomForestClassifier does not check for NaN and inf",
        "check_classifier_data_not_an_array": "RandomForestClassifier does not handle non-array data",
        "check_classifiers_train": "RandomForestClassifier does not handle list inputs",
        "check_classifiers_train(readonly_memmap=True)": "RandomForestClassifier does not handle readonly memmap",
        "check_classifiers_train(readonly_memmap=True,X_dtype=float32)": "RandomForestClassifier does not handle readonly memmap with float32",
        "check_supervised_y_no_nan": "RandomForestClassifier does not check for NaN in y",
        "check_supervised_y_2d": "RandomForestClassifier does not handle 2D y",
        "check_dict_unchanged": "RandomForestClassifier modifies input dictionaries",
        "check_fit2d_predict1d": "RandomForestClassifier does not handle 1D prediction input gracefully",
    },
    KNeighborsRegressor: {
        "check_estimator_tags_renamed": "No support for modern tags infrastructure",
        "check_no_attributes_set_in_init": "KNeighborsRegressor sets attributes during init",
        "check_estimators_unfitted": "KNeighborsRegressor does not raise NotFittedError before fit",
        "check_do_not_raise_errors_in_init_or_set_params": "KNeighborsRegressor raises errors in init or set_params",
        "check_n_features_in_after_fitting": "KNeighborsRegressor does not check n_features_in consistency",
        "check_dtype_object": "KNeighborsRegressor does not handle object dtype",
        "check_estimators_empty_data_messages": "KNeighborsRegressor does not handle empty data",
        "check_estimators_nan_inf": "KNeighborsRegressor does not check for NaN and inf",
        "check_regressors_train": "KNeighborsRegressor does not handle list inputs",
        "check_regressors_train(readonly_memmap=True)": "KNeighborsRegressor does not handle readonly memmap",
        "check_regressors_train(readonly_memmap=True,X_dtype=float32)": "KNeighborsRegressor does not handle readonly memmap with float32",
        "check_regressor_data_not_an_array": "KNeighborsRegressor does not handle non-array data",
        "check_supervised_y_2d": "KNeighborsRegressor does not handle 2D y",
        "check_supervised_y_no_nan": "KNeighborsRegressor does not check for NaN in y",
        "check_fit_check_is_fitted": "KNeighborsRegressor passes check_is_fitted before being fit",
    },
    NearestNeighbors: {
        "check_estimator_tags_renamed": "No support for modern tags infrastructure",
        "check_no_attributes_set_in_init": "NearestNeighbors sets attributes during init",
        "check_dtype_object": "NearestNeighbors does not handle object dtype",
        "check_estimators_empty_data_messages": "NearestNeighbors does not handle empty data",
        "check_estimators_nan_inf": "NearestNeighbors does not check for NaN and inf",
        "check_fit_check_is_fitted": "NearestNeighbors passes check_is_fitted before being fit",
    },
    LinearSVC: {
        "check_estimator_tags_renamed": "No support for modern tags infrastructure",
        "check_estimators_unfitted": "LinearSVC does not raise NotFittedError before fit",
        "check_n_features_in_after_fitting": "LinearSVC does not check n_features_in consistency",
        "check_estimators_dtypes": "LinearSVC does not handle dtypes properly",
        "check_sample_weights_not_an_array": "LinearSVC does not handle non-array sample weights",
        "check_sample_weights_list": "LinearSVC does not handle list sample weights",
        "check_sample_weight_equivalence_on_dense_data": "LinearSVC sample weight equivalence not implemented",
        "check_all_zero_sample_weights_error": "LinearSVC does not validate all-zero sample weights",
        "check_dtype_object": "LinearSVC does not handle object dtype",
        "check_estimators_nan_inf": "LinearSVC does not check for NaN and inf",
        "check_estimators_pickle": "LinearSVC does not support pickling",
        "check_estimators_pickle(readonly_memmap=True)": "LinearSVC does not support pickling with readonly memmap",
        "check_classifier_data_not_an_array": "LinearSVC does not handle non-array data",
        "check_classifiers_train": "LinearSVC does not handle list inputs",
        "check_classifiers_train(readonly_memmap=True)": "LinearSVC does not handle readonly memmap",
        "check_classifiers_train(readonly_memmap=True,X_dtype=float32)": "LinearSVC does not handle readonly memmap with float32",
        "check_supervised_y_2d": "LinearSVC does not handle 2D y",
        "check_decision_proba_consistency": "LinearSVC does not support predict_proba",
        "check_methods_sample_order_invariance": "LinearSVC results depend on sample order",
        "check_methods_subset_invariance": "LinearSVC results depend on data subset",
        "check_dict_unchanged": "LinearSVC modifies input dictionaries",
        "check_fit_idempotent": "LinearSVC fit is not idempotent",
        "check_fit2d_predict1d": "LinearSVC does not handle 1D prediction input gracefully",
    },
    LinearSVR: {
        "check_estimator_tags_renamed": "No support for modern tags infrastructure",
        "check_sample_weights_not_an_array": "LinearSVR does not handle non-array sample weights",
        "check_sample_weights_list": "LinearSVR does not handle list sample weights",
        "check_sample_weight_equivalence_on_dense_data": "LinearSVR sample weight equivalence not implemented",
        "check_all_zero_sample_weights_error": "LinearSVR does not validate all-zero sample weights",
        "check_dtype_object": "LinearSVR does not handle object dtype",
        "check_estimators_nan_inf": "LinearSVR does not check for NaN and inf",
        "check_regressors_train": "LinearSVR does not handle list inputs",
        "check_regressors_train(readonly_memmap=True)": "LinearSVR does not handle readonly memmap",
        "check_regressors_train(readonly_memmap=True,X_dtype=float32)": "LinearSVR does not handle readonly memmap with float32",
        "check_regressor_data_not_an_array": "LinearSVR does not handle non-array data",
        "check_supervised_y_2d": "LinearSVR does not handle 2D y",
        "check_supervised_y_no_nan": "LinearSVR does not check for NaN in y",
    },
    SVC: {
        "check_estimator_tags_renamed": "No support for modern tags infrastructure",
        "check_estimators_unfitted": "SVC does not raise NotFittedError before fit",
        "check_n_features_in_after_fitting": "SVC does not check n_features_in consistency",
        "check_estimators_dtypes": "SVC does not handle dtypes properly",
        "check_sample_weights_not_an_array": "SVC does not handle non-array sample weights",
        "check_sample_weight_equivalence_on_dense_data": "SVC sample weight equivalence not implemented",
        "check_sample_weight_equivalence_on_sparse_data": "SVC does not handle sparse data",
        "check_all_zero_sample_weights_error": "SVC does not validate all-zero sample weights",
        "check_dtype_object": "SVC does not handle object dtype",
        "check_estimators_nan_inf": "SVC does not check for NaN and inf",
        "check_estimator_sparse_array": "SVC does not handle sparse arrays gracefully",
        "check_estimator_sparse_matrix": "SVC does not handle sparse matrices gracefully",
        "check_estimators_pickle": "SVC does not support pickling",
        "check_estimators_pickle(readonly_memmap=True)": "SVC does not support pickling with readonly memmap",
        "check_classifier_data_not_an_array": "SVC does not handle non-array data",
        "check_classifiers_train": "SVC does not handle list inputs",
        "check_classifiers_train(readonly_memmap=True)": "SVC does not handle readonly memmap",
        "check_classifiers_train(readonly_memmap=True,X_dtype=float32)": "SVC does not handle readonly memmap with float32",
        "check_decision_proba_consistency": "SVC does not support predict_proba by default",
        "check_methods_sample_order_invariance": "SVC results depend on sample order",
        "check_methods_subset_invariance": "SVC results depend on data subset",
        "check_dict_unchanged": "SVC modifies input dictionaries",
        "check_fit_idempotent": "SVC fit is not idempotent",
        "check_fit2d_predict1d": "SVC does not handle 1D prediction input gracefully",
        "check_sample_weights_list": "SVC does not handle list sample weights",
        "check_supervised_y_2d": "SVC does not warn on 1 column 2D y",
    },
    SVR: {
        "check_estimator_tags_renamed": "No support for modern tags infrastructure",
        "check_sample_weights_not_an_array": "SVR does not handle non-array sample weights",
        "check_sample_weights_list": "SVR does not handle list sample weights",
        "check_sample_weight_equivalence_on_dense_data": "SVR sample weight equivalence not implemented",
        "check_sample_weight_equivalence_on_sparse_data": "SVR does not handle sparse data",
        "check_all_zero_sample_weights_error": "SVR does not validate all-zero sample weights",
        "check_dtype_object": "SVR does not handle object dtype",
        "check_estimators_nan_inf": "SVR does not check for NaN and inf",
        "check_regressors_train": "SVR does not handle list inputs",
        "check_regressors_train(readonly_memmap=True)": "SVR does not handle readonly memmap",
        "check_regressors_train(readonly_memmap=True,X_dtype=float32)": "SVR does not handle readonly memmap with float32",
        "check_regressor_data_not_an_array": "SVR does not handle non-array data",
        "check_supervised_y_2d": "SVR does not handle 2D y",
        "check_supervised_y_no_nan": "SVR does not check for NaN in y",
    },
    PCA: {
        "check_estimator_tags_renamed": "No support for modern tags infrastructure",
        "check_dtype_object": "PCA does not handle object dtype",
        "check_estimators_empty_data_messages": "PCA does not handle empty data",
        "check_estimators_nan_inf": "PCA does not check for NaN and inf",
        "check_transformer_data_not_an_array": "PCA does not handle non-array data",
        "check_fit2d_1sample": "PCA does not handle single sample",
        "check_fit2d_1feature": "PCA does not handle single feature",
    },
    IncrementalPCA: {
        "check_estimator_tags_renamed": "No support for modern tags infrastructure",
        "check_n_features_in_after_fitting": "IncrementalPCA does not check n_features_in consistency",
        "check_dtype_object": "IncrementalPCA does not handle object dtype",
        "check_estimators_empty_data_messages": "IncrementalPCA does not handle empty data",
        "check_estimators_nan_inf": "IncrementalPCA does not check for NaN and inf",
        "check_transformer_data_not_an_array": "IncrementalPCA does not handle non-array data",
    },
    TruncatedSVD: {
        "check_estimator_tags_renamed": "No support for modern tags infrastructure",
        "check_dtype_object": "TruncatedSVD does not handle object dtype",
        "check_estimators_empty_data_messages": "TruncatedSVD does not handle empty data",
        "check_estimators_nan_inf": "TruncatedSVD does not check for NaN and inf",
        "check_transformer_data_not_an_array": "TruncatedSVD does not handle non-array data",
        "check_fit2d_1sample": "TruncatedSVD does not handle single sample",
        "check_fit2d_1feature": "TruncatedSVD does not handle single feature",
    },
    TSNE: {
        "check_estimator_tags_renamed": "No support for modern tags infrastructure",
        "check_dont_overwrite_parameters": "TSNE overwrites parameters during fit",
        "check_dtype_object": "TSNE does not handle object dtype",
        "check_estimators_empty_data_messages": "TSNE does not handle empty data",
        "check_pipeline_consistency": "TSNE results are not deterministic",
        "check_estimators_nan_inf": "TSNE does not check for NaN and inf",
        "check_methods_sample_order_invariance": "TSNE results depend on sample order",
        "check_methods_subset_invariance": "TSNE results depend on data subset",
        "check_fit2d_1sample": "TSNE does not handle single sample",
        "check_fit2d_1feature": "TSNE does not handle single feature",
        "check_fit2d_predict1d": "TSNE does not handle 1D prediction input gracefully",
    },
    UMAP: {
        "check_estimator_tags_renamed": "No support for modern tags infrastructure",
        "check_dtype_object": "UMAP does not handle object dtype",
        "check_transformer_data_not_an_array": "UMAP does not handle non-array data",
        "check_methods_sample_order_invariance": "UMAP results depend on sample order",
        "check_transformer_general": "UMAP does not have consistent fit_transform and transform outputs",
        "check_methods_subset_invariance": "UMAP results depend on data subset",
    },
    Lasso: {
        "check_estimator_tags_renamed": "No support for modern tags infrastructure",
        "check_sample_weights_not_an_array": "Lasso does not handle non-array sample weights",
        "check_sample_weights_list": "Lasso does not handle list sample weights",
        "check_all_zero_sample_weights_error": "Lasso does not validate all-zero sample weights",
        "check_dtype_object": "Lasso does not handle object dtype",
        "check_estimators_nan_inf": "Lasso does not check for NaN and inf",
        "check_regressors_train": "Lasso does not handle list inputs",
        "check_regressors_train(readonly_memmap=True)": "Lasso does not handle readonly memmap",
        "check_regressors_train(readonly_memmap=True,X_dtype=float32)": "Lasso does not handle readonly memmap with float32",
        "check_regressor_data_not_an_array": "Lasso does not handle non-array data",
        "check_supervised_y_2d": "Lasso does not handle 2D y",
        "check_supervised_y_no_nan": "Lasso does not check for NaN in y",
    },
    ElasticNet: {
        "check_estimator_tags_renamed": "No support for modern tags infrastructure",
        "check_sample_weights_not_an_array": "ElasticNet does not handle non-array sample weights",
        "check_sample_weights_list": "ElasticNet does not handle list sample weights",
        "check_all_zero_sample_weights_error": "ElasticNet does not validate all-zero sample weights",
        "check_dtype_object": "ElasticNet does not handle object dtype",
        "check_estimators_nan_inf": "ElasticNet does not check for NaN and inf",
        "check_regressors_train": "ElasticNet does not handle list inputs",
        "check_regressors_train(readonly_memmap=True)": "ElasticNet does not handle readonly memmap",
        "check_regressors_train(readonly_memmap=True,X_dtype=float32)": "ElasticNet does not handle readonly memmap with float32",
        "check_regressor_data_not_an_array": "ElasticNet does not handle non-array data",
        "check_supervised_y_2d": "ElasticNet does not handle 2D y",
        "check_supervised_y_no_nan": "ElasticNet does not check for NaN in y",
    },
    KernelDensity: {
        "check_estimator_tags_renamed": "No support for modern tags infrastructure",
        "check_n_features_in_after_fitting": "KernelDensity does not check n_features_in consistency",
        "check_sample_weights_not_an_array": "KernelDensity does not handle non-array sample weights",
        "check_sample_weights_list": "KernelDensity does not handle list sample weights",
        "check_all_zero_sample_weights_error": "KernelDensity does not validate all-zero sample weights",
        "check_dtype_object": "KernelDensity does not handle object dtype",
        "check_estimators_nan_inf": "KernelDensity does not check for NaN and inf",
    },
    LedoitWolf: {
        "check_estimator_tags_renamed": "No support for modern tags infrastructure",
        "check_n_features_in_after_fitting": "LedoitWolf does not check n_features_in consistency",
        "check_dtype_object": "LedoitWolf does not handle object dtype",
        "check_estimators_empty_data_messages": "LedoitWolf does not handle empty data",
        "check_estimators_nan_inf": "LedoitWolf does not check for NaN and inf",
    },
    DBSCAN: {
        "check_estimator_tags_renamed": "No support for modern tags infrastructure",
        "check_sample_weights_not_an_array": "DBSCAN does not handle non-array sample weights",
        "check_sample_weights_list": "DBSCAN does not handle list sample weights",
        "check_all_zero_sample_weights_error": "DBSCAN does not validate all-zero sample weights",
        "check_dtype_object": "DBSCAN does not handle object dtype",
        "check_estimators_empty_data_messages": "DBSCAN does not handle empty data",
        "check_estimators_nan_inf": "DBSCAN does not check for NaN and inf",
    },
    HDBSCAN: {
        "check_estimator_tags_renamed": "No support for modern tags infrastructure",
        "check_no_attributes_set_in_init": "HDBSCAN sets attributes during init",
        "check_do_not_raise_errors_in_init_or_set_params": "HDBSCAN raises errors in init or set_params",
        "check_dtype_object": "HDBSCAN does not handle object dtype",
        "check_estimators_empty_data_messages": "HDBSCAN does not handle empty data",
        "check_estimators_nan_inf": "HDBSCAN does not check for NaN and inf",
        "check_estimator_sparse_array": "HDBSCAN does not handle sparse arrays gracefully",
        "check_estimator_sparse_matrix": "HDBSCAN does not handle sparse matrices gracefully",
        "check_parameters_default_constructible": "HDBSCAN parameters are mutated on init",
        "check_estimators_pickle": "HDBSCAN does not support pickling",
        "check_estimators_pickle(readonly_memmap=True)": "HDBSCAN does not support pickling with readonly memmap",
        "check_f_contiguous_array_estimator": "HDBSCAN does not handle F-contiguous arrays",
        "check_methods_sample_order_invariance": "HDBSCAN results depend on sample order",
        "check_methods_subset_invariance": "HDBSCAN results depend on data subset",
        "check_fit2d_1sample": "HDBSCAN does not handle single sample properly",
        "check_fit2d_1feature": "HDBSCAN does not handle single feature properly",
        "check_dict_unchanged": "HDBSCAN modifies input dictionaries",
        "check_fit_idempotent": "HDBSCAN fit is not idempotent",
        "check_fit_check_is_fitted": "HDBSCAN does not check is_fitted properly",
        "check_n_features_in": "HDBSCAN does not set n_features_in properly",
        "check_fit1d": "HDBSCAN does not raise ValueError for 1D input",
        "check_fit2d_predict1d": "HDBSCAN does not handle 1D prediction input gracefully",
    },
    AgglomerativeClustering: {
        "check_estimator_tags_renamed": "No support for modern tags infrastructure",
        "check_no_attributes_set_in_init": "AgglomerativeClustering sets attributes during init",
        "check_do_not_raise_errors_in_init_or_set_params": "AgglomerativeClustering raises errors in init or set_params",
        "check_dtype_object": "AgglomerativeClustering does not handle object dtype",
        "check_estimators_nan_inf": "AgglomerativeClustering does not check for NaN and inf",
        "check_estimator_sparse_array": "AgglomerativeClustering does not handle sparse arrays gracefully",
        "check_estimator_sparse_matrix": "AgglomerativeClustering does not handle sparse matrices gracefully",
        "check_parameters_default_constructible": "AgglomerativeClustering parameters are mutated on init",
        "check_fit1d": "AgglomerativeClustering does not raise ValueError for 1D input",
    },
    GaussianNB: {
        "check_estimator_tags_renamed": "No support for modern tags infrastructure",
        "check_estimators_unfitted": "GaussianNB does not raise NotFittedError before fit",
        "check_n_features_in_after_fitting": "GaussianNB does not check n_features_in consistency",
        "check_estimators_dtypes": "GaussianNB does not handle dtypes properly",
        "check_sample_weights_pandas_series": "GaussianNB does not handle pandas Series sample weights",
        "check_sample_weights_not_an_array": "GaussianNB does not handle non-array sample weights",
        "check_sample_weights_shape": "GaussianNB does not validate sample weights shape",
        "check_all_zero_sample_weights_error": "GaussianNB does not validate all-zero sample weights",
        "check_dtype_object": "GaussianNB does not handle object dtype",
        "check_estimators_empty_data_messages": "GaussianNB does not handle empty data",
        "check_estimators_nan_inf": "GaussianNB does not check for NaN and inf",
        "check_classifier_data_not_an_array": "GaussianNB does not handle non-array data",
        "check_classifiers_classes": "GaussianNB does not handle string data properly",
        "check_estimators_partial_fit_n_features": "GaussianNB does not check n_features consistency in partial_fit",
        "check_classifiers_train": "GaussianNB does not handle list inputs",
        "check_classifiers_train(readonly_memmap=True)": "GaussianNB does not handle readonly memmap",
        "check_classifiers_train(readonly_memmap=True,X_dtype=float32)": "GaussianNB does not handle readonly memmap with float32",
        "check_classifiers_regression_target": "GaussianNB does not handle regression targets",
        "check_supervised_y_no_nan": "GaussianNB does not check for NaN in y",
        "check_supervised_y_2d": "GaussianNB does not handle 2D y",
        "check_fit2d_predict1d": "GaussianNB does not handle 1D prediction input gracefully",
        "check_sample_weights_list": "GaussianNB does not handle list sample weights",
    },
    GaussianRandomProjection: {
        "check_estimator_tags_renamed": "No support for modern tags infrastructure",
        "check_fit_score_takes_y": "GaussianRandomProjection raises ValueError with small datasets",
        "check_estimators_overwrite_params": "GaussianRandomProjection raises ValueError with small datasets",
        "check_estimators_fit_returns_self": "GaussianRandomProjection raises ValueError with small datasets",
        "check_readonly_memmap_input": "GaussianRandomProjection raises ValueError with small datasets",
        "check_n_features_in_after_fitting": "GaussianRandomProjection raises ValueError with small datasets",
        "check_positive_only_tag_during_fit": "GaussianRandomProjection raises ValueError with small datasets",
        "check_estimators_dtypes": "GaussianRandomProjection raises ValueError with small datasets",
        "check_complex_data": "GaussianRandomProjection raises ValueError with small datasets",
        "check_dtype_object": "GaussianRandomProjection raises ValueError with small datasets",
        "check_estimators_empty_data_messages": "GaussianRandomProjection does not handle empty data",
        "check_pipeline_consistency": "GaussianRandomProjection raises ValueError with small datasets",
        "check_estimators_nan_inf": "GaussianRandomProjection does not check for NaN and inf",
        "check_estimator_sparse_tag": "GaussianRandomProjection raises ValueError with small datasets even though it supports sparse inputs",
        "check_estimator_sparse_array": "GaussianRandomProjection does not handle sparse arrays gracefully",
        "check_estimator_sparse_matrix": "GaussianRandomProjection does not handle sparse matrices gracefully",
        "check_estimators_pickle": "GaussianRandomProjection raises ValueError with small datasets",
        "check_estimators_pickle(readonly_memmap=True)": "GaussianRandomProjection raises ValueError with small datasets",
        "check_f_contiguous_array_estimator": "GaussianRandomProjection raises ValueError with small datasets",
        "check_transformer_data_not_an_array": "GaussianRandomProjection does not handle non-array data",
        "check_transformer_general": "GaussianRandomProjection raises ValueError with small datasets",
        "check_transformer_general(readonly_memmap=True)": "GaussianRandomProjection raises ValueError with small datasets",
        "check_dict_unchanged": "GaussianRandomProjection raises ValueError with small datasets",
        "check_fit_idempotent": "GaussianRandomProjection raises ValueError with small datasets",
        "check_fit_check_is_fitted": "GaussianRandomProjection raises ValueError with small datasets",
        "check_n_features_in": "GaussianRandomProjection raises ValueError with small datasets",
    },
    SparseRandomProjection: {
        "check_estimator_tags_renamed": "No support for modern tags infrastructure",
        "check_fit_score_takes_y": "SparseRandomProjection raises ValueError with small datasets",
        "check_estimators_overwrite_params": "SparseRandomProjection raises ValueError with small datasets",
        "check_estimators_fit_returns_self": "SparseRandomProjection raises ValueError with small datasets",
        "check_readonly_memmap_input": "SparseRandomProjection raises ValueError with small datasets",
        "check_n_features_in_after_fitting": "SparseRandomProjection raises ValueError with small datasets",
        "check_positive_only_tag_during_fit": "SparseRandomProjection raises ValueError with small datasets",
        "check_estimators_dtypes": "SparseRandomProjection raises ValueError with small datasets",
        "check_complex_data": "SparseRandomProjection raises ValueError with small datasets",
        "check_dtype_object": "SparseRandomProjection raises ValueError with small datasets",
        "check_estimators_empty_data_messages": "SparseRandomProjection does not handle empty data",
        "check_pipeline_consistency": "SparseRandomProjection raises ValueError with small datasets",
        "check_estimators_nan_inf": "SparseRandomProjection does not check for NaN and inf",
        "check_estimator_sparse_tag": "SparseRandomProjection raises ValueError with small datasets",
        "check_estimator_sparse_array": "SparseRandomProjection does not handle sparse arrays gracefully",
        "check_estimator_sparse_matrix": "SparseRandomProjection does not handle sparse matrices gracefully",
        "check_estimators_pickle": "SparseRandomProjection raises ValueError with small datasets",
        "check_estimators_pickle(readonly_memmap=True)": "SparseRandomProjection raises ValueError with small datasets",
        "check_f_contiguous_array_estimator": "SparseRandomProjection raises ValueError with small datasets",
        "check_transformer_data_not_an_array": "SparseRandomProjection does not handle non-array data",
        "check_transformer_general": "SparseRandomProjection raises ValueError with small datasets",
        "check_transformer_general(readonly_memmap=True)": "SparseRandomProjection raises ValueError with small datasets",
        "check_dict_unchanged": "SparseRandomProjection raises ValueError with small datasets",
        "check_fit_idempotent": "SparseRandomProjection raises ValueError with small datasets",
        "check_fit_check_is_fitted": "SparseRandomProjection raises ValueError with small datasets",
        "check_n_features_in": "SparseRandomProjection raises ValueError with small datasets",
    },
    BernoulliNB: {
        "check_estimator_tags_renamed": "No support for modern tags infrastructure",
        "check_estimators_unfitted": "BernoulliNB does not raise NotFittedError before fit",
        "check_n_features_in_after_fitting": "BernoulliNB does not check n_features_in consistency",
        "check_estimators_dtypes": "BernoulliNB expects specific dtypes, not bool",
        "check_sample_weights_pandas_series": "BernoulliNB does not handle pandas Series sample weights",
        "check_sample_weights_not_an_array": "BernoulliNB does not handle non-array sample weights",
        "check_sample_weights_shape": "BernoulliNB does not validate sample weights shape",
        "check_sample_weight_equivalence_on_dense_data": "BernoulliNB sample weight equivalence not implemented",
        "check_all_zero_sample_weights_error": "BernoulliNB does not validate all-zero sample weights",
        "check_dtype_object": "BernoulliNB does not handle object dtype",
        "check_estimators_empty_data_messages": "BernoulliNB does not provide proper error messages for empty data",
        "check_estimators_nan_inf": "BernoulliNB does not check for NaN and inf",
        "check_classifier_data_not_an_array": "BernoulliNB does not handle list inputs",
        "check_classifiers_classes": "BernoulliNB does not handle string labels properly",
        "check_estimators_partial_fit_n_features": "BernoulliNB does not check n_features consistency in partial_fit",
        "check_classifiers_train": "BernoulliNB does not handle list inputs",
        "check_classifiers_train(readonly_memmap=True)": "BernoulliNB does not handle list inputs",
        "check_classifiers_train(readonly_memmap=True,X_dtype=float32)": "BernoulliNB does not handle list inputs",
        "check_classifiers_regression_target": "BernoulliNB does not validate target is classification",
        "check_supervised_y_no_nan": "BernoulliNB does not check for NaN in y",
        "check_supervised_y_2d": "BernoulliNB does not handle 2D y input gracefully",
        "check_fit2d_predict1d": "BernoulliNB does not handle 1D prediction input gracefully",
    },
    ComplementNB: {
        "check_estimator_tags_renamed": "No support for modern tags infrastructure",
        "check_estimators_overwrite_params": "ComplementNB overwrites params on clone",
        "check_estimators_fit_returns_self": "ComplementNB fit does not return self for certain data types",
        "check_readonly_memmap_input": "ComplementNB does not handle readonly memmap input",
        "check_estimators_unfitted": "ComplementNB does not raise NotFittedError before fit",
        "check_n_features_in_after_fitting": "ComplementNB does not check n_features_in consistency",
        "check_positive_only_tag_during_fit": "ComplementNB does not validate positive-only requirement",
        "check_estimators_dtypes": "ComplementNB expects specific dtypes, not bool",
        "check_sample_weights_pandas_series": "ComplementNB does not handle pandas Series sample weights",
        "check_sample_weights_not_an_array": "ComplementNB does not handle non-array sample weights",
        "check_sample_weights_shape": "ComplementNB does not validate sample weights shape",
        "check_sample_weight_equivalence_on_dense_data": "ComplementNB sample weight equivalence not implemented",
        "check_all_zero_sample_weights_error": "ComplementNB does not validate all-zero sample weights",
        "check_dtype_object": "ComplementNB does not handle object dtype",
        "check_estimators_empty_data_messages": "ComplementNB does not provide proper error messages for empty data",
        "check_pipeline_consistency": "ComplementNB pipeline consistency issues",
        "check_estimators_nan_inf": "ComplementNB does not check for NaN and inf",
        "check_estimators_pickle": "ComplementNB pickling issues",
        "check_estimators_pickle(readonly_memmap=True)": "ComplementNB pickling with readonly memmap issues",
        "check_classifier_data_not_an_array": "ComplementNB does not handle list inputs",
        "check_classifiers_classes": "ComplementNB does not handle string labels properly",
        "check_estimators_partial_fit_n_features": "ComplementNB does not check n_features consistency in partial_fit",
        "check_classifiers_train": "ComplementNB does not handle list inputs",
        "check_classifiers_train(readonly_memmap=True)": "ComplementNB does not handle list inputs",
        "check_classifiers_train(readonly_memmap=True,X_dtype=float32)": "ComplementNB does not handle list inputs",
        "check_classifiers_regression_target": "ComplementNB does not validate target is classification",
        "check_supervised_y_no_nan": "ComplementNB does not check for NaN in y",
        "check_supervised_y_2d": "ComplementNB does not handle 2D y input gracefully",
        "check_fit2d_predict1d": "ComplementNB does not handle 1D prediction input gracefully",
    },
    CategoricalNB: {
        "check_estimator_tags_renamed": "No support for modern tags infrastructure",
        "check_estimators_overwrite_params": "CategoricalNB overwrites params on clone",
        "check_estimators_fit_returns_self": "CategoricalNB fit does not return self for certain data types",
        "check_readonly_memmap_input": "CategoricalNB does not handle readonly memmap input",
        "check_estimators_unfitted": "CategoricalNB does not raise NotFittedError before fit",
        "check_n_features_in_after_fitting": "CategoricalNB does not check n_features_in consistency",
        "check_positive_only_tag_during_fit": "CategoricalNB does not validate positive-only requirement",
        "check_estimators_dtypes": "CategoricalNB expects specific dtypes, not bool",
        "check_sample_weights_pandas_series": "CategoricalNB does not handle pandas Series sample weights",
        "check_sample_weights_not_an_array": "CategoricalNB does not handle non-array sample weights",
        "check_sample_weights_shape": "CategoricalNB does not validate sample weights shape",
        "check_sample_weight_equivalence_on_dense_data": "CategoricalNB sample weight equivalence not implemented",
        "check_all_zero_sample_weights_error": "CategoricalNB does not validate all-zero sample weights",
        "check_dtype_object": "CategoricalNB does not handle object dtype",
        "check_estimators_empty_data_messages": "CategoricalNB does not provide proper error messages for empty data",
        "check_estimators_nan_inf": "CategoricalNB does not check for NaN and inf",
        "check_classifier_data_not_an_array": "CategoricalNB does not handle list inputs",
        "check_classifiers_classes": "CategoricalNB does not handle string labels properly",
        "check_estimators_partial_fit_n_features": "CategoricalNB does not check n_features consistency in partial_fit",
        "check_classifiers_train": "CategoricalNB does not handle list inputs",
        "check_classifiers_train(readonly_memmap=True)": "CategoricalNB does not handle list inputs",
        "check_classifiers_train(readonly_memmap=True,X_dtype=float32)": "CategoricalNB does not handle list inputs",
        "check_classifiers_regression_target": "CategoricalNB does not validate target is classification",
        "check_supervised_y_no_nan": "CategoricalNB does not check for NaN in y",
        "check_supervised_y_2d": "CategoricalNB does not handle 2D y input gracefully",
        "check_fit2d_predict1d": "CategoricalNB does not handle 1D prediction input gracefully",
    },
    MultinomialNB: {
        "check_estimator_tags_renamed": "No support for modern tags infrastructure",
        "check_estimators_unfitted": "MultinomialNB does not raise NotFittedError before fit",
        "check_n_features_in_after_fitting": "MultinomialNB does not check n_features_in consistency",
        "check_estimators_dtypes": "MultinomialNB does not handle all dtypes properly",
        "check_sample_weights_pandas_series": "MultinomialNB does not handle pandas Series sample weights",
        "check_sample_weights_not_an_array": "MultinomialNB does not handle non-array sample weights",
        "check_sample_weights_shape": "MultinomialNB does not validate sample weights shape",
        "check_sample_weight_equivalence_on_dense_data": "MultinomialNB sample weight equivalence not implemented",
        "check_all_zero_sample_weights_error": "MultinomialNB does not validate all-zero sample weights",
        "check_dtype_object": "MultinomialNB does not handle object dtype",
        "check_estimators_empty_data_messages": "MultinomialNB does not provide proper error messages for empty data",
        "check_estimators_nan_inf": "MultinomialNB does not check for NaN and inf",
        "check_classifier_data_not_an_array": "MultinomialNB does not handle non-array data",
        "check_classifiers_classes": "MultinomialNB does not handle string labels properly",
        "check_estimators_partial_fit_n_features": "MultinomialNB does not check n_features consistency in partial_fit",
        "check_classifiers_train": "MultinomialNB does not validate X and y shapes are consistent",
        "check_classifiers_train(readonly_memmap=True)": "MultinomialNB does not validate X and y shapes are consistent",
        "check_classifiers_train(readonly_memmap=True,X_dtype=float32)": "MultinomialNB does not validate X and y shapes are consistent",
        "check_classifiers_regression_target": "MultinomialNB does not validate target is classification",
        "check_supervised_y_no_nan": "MultinomialNB does not check for NaN in y",
        "check_supervised_y_2d": "MultinomialNB does not handle 2D y input gracefully",
        "check_fit2d_predict1d": "MultinomialNB does not handle 1D prediction input gracefully",
    },
}


def get_xfails(estimator):
    return PER_ESTIMATOR_XFAIL_CHECKS.get(type(estimator), {})


def _check_name(check):
    if hasattr(check, "__wrapped__"):
        return _check_name(check.__wrapped__)
    return (
        check.func.__name__ if isinstance(check, partial) else check.__name__
    )


@estimator_checks.parametrize_with_checks(
    [
        GaussianRandomProjection(),
        SparseRandomProjection(),
        DBSCAN(),
        AgglomerativeClustering(),
        KernelRidge(),
        GaussianNB(),
        ComplementNB(),
        CategoricalNB(),
        BernoulliNB(),
        MultinomialNB(),
        UMAP(),
        TSNE(),
        TruncatedSVD(),
        IncrementalPCA(),
        PCA(),
        SVR(),
        SVC(),
        LinearSVR(),
        LinearSVC(),
        NearestNeighbors(),
        KNeighborsRegressor(),
        KNeighborsClassifier(),
        KernelDensity(),
        LedoitWolf(),
        Ridge(),
        ElasticNet(),
        Lasso(),
        LinearRegression(),
        RandomForestClassifier(),
        RandomForestRegressor(),
        KMeans(),
        LogisticRegression(),
    ],
    expected_failed_checks=get_xfails,
    xfail_strict=True,
)
@pytest.mark.filterwarnings(
    "ignore:ValueError occurred during set_params.*:UserWarning"
)
@pytest.mark.filterwarnings(
    "ignore:TypeError occurred during set_params.*:UserWarning"
)
@pytest.mark.filterwarnings(
    "ignore:perplexity.*should be less than n_samples.*:UserWarning"
)
@pytest.mark.filterwarnings(
    "ignore:Estimator's parameters changed after set_params raised ValueError:UserWarning"
)
@pytest.mark.filterwarnings("ignore:Changing solver to 'svd'.*:UserWarning")
@pytest.mark.filterwarnings("ignore:The number of bins.*:UserWarning")
@pytest.mark.filterwarnings("ignore::pytest.PytestUnraisableExceptionWarning")
def test_sklearn_compatible_estimator(estimator, check):
    # Check that all estimators pass the "common estimator" checks
    # provided by scikit-learn

    # These estimators lead to additional MemoryErrors in the other
    # estimators. As a result they are currently skipped.
    if isinstance(estimator, AgglomerativeClustering):
        pytest.skip(
            "Estimator sometimes causes persistent memory errors (gh-7345)"
        )

    check_name = _check_name(check)

    if check_name in ["check_estimators_nan_inf"] and isinstance(
        estimator, UMAP
    ):
        pytest.skip("UMAP does not handle Nans and infinities")

    check(estimator)
