#!/bin/bash

#FIXME Remove this folder before merge

RF_BASE_DIR="/gpfs/fs1/myrtop/rapids_repos/regression_random_forest/cuml"
#Compile
nvcc -std=c++11 -arch=sm_70 rf_testing.cu ../../decisiontree/decisiontree.cu ../../common/cuml_api.cpp ../../common/cumlHandle.cpp -I$RF_BASE_DIR/ml-prims/src/ -I$RF_BASE_DIR/cuML/external/ml-prims/external/cub -I$RF_BASE_DIR/cuML/src -I$RF_BASE_DIR/thirdparty/cuml/ml-prims/src/ -lcublas -lcudart -lcusolver -lcusparse --expt-extended-lambda  -o rf_testing

if [ ! -e rf_testing ]; then
	echo "Error in building tmp_rf_testing"
	exit
fi

# --------- Year Dataset ------------ #
dataset="year"
cols=90 #Note doesn't matter will be fixed in tmp_rf_testing
rows=515345

# --------- Airline Dataset ------------ #
#dataset="airline_regression"
#dataset="airline"
#cols=13 #Note: doesn't matter will be fixed in tmp_rf_testing
#rows=115069017

trees=1
col_per=1.0
row_per=1.0
train_ratio=0.8

max_depth=8
#max_depth=-1
max_leaves=-1
bootstrap=false
test_is_train=false
#test_is_train=true
n_bins=8
split_algo=1 #0 means hist, 1 means global quantiles
split_criterion=4; #0 is GINI, 1 is ENTROPY, 2 is MSE, 3 is MAE, 4 enforces default (GINI or MSE respectively).

echo "./rf_testing $rows $cols $trees $col_per $row_per $train_ratio $max_depth $max_leaves $bootstrap $test_is_train $n_bins $dataset $split_algo $split_criterion"
./rf_testing $rows $cols $trees $col_per $row_per $train_ratio $max_depth $max_leaves $bootstrap $test_is_train $n_bins $dataset $split_algo $split_criterion

