include "pca/pca_wrapper.pyx"
include "tsvd/tsvd_wrapper.pyx"
include "dbscan/dbscan_wrapper.pyx"
include "kmeans/kmeans_wrapper.pyx"
include "linear_model/linear_regression.pyx"
#include "knn/knn_wrapper.pyx"
