#!/bin/bash

rows=1000
cols=28 #for higgs
trees=1
col_per=1.0
row_per=1.0
train_ratio=0.8

max_depth=-1
max_leaves=-1
bootstrap=true
test_is_train=true
n_bins=8


./rf_testing $rows $cols $trees $col_per $row_per $train_ratio $max_depth $max_leaves $bootstrap $test_is_train $n_bins
